### ISSUE TITLE
new image options

### ISSUE THREAD

**Issue by the-simian** [pahen/madge#101]
Thanks for the great module! I was trying to migrate to the latest version when I noticed you switched over to a promise-based api, which is very nice. Unfortunately, I couldn't find how to update the options for the `.image()`. Before you'd call

```js
  dependencyObject.image(imageOpts, (img)=>{
    fs.writefile('path/to/file', img, function cb(){})
   });
```

where the imageOptions was an object you could use to change things about the file, such as the layout, font size and colors.

what is the new way to do this? I see an image function but it only takes a path, and not the ability to take options and specify the other layouts.

thanks!

**Comment by pahen** [comment]
Hi and thanks!

You need to pass in the config as the second argument to `madge()`. See https://github.com/pahen/madge#madgepath-stringarray-config-object. So in your case it would be something like:

```javascript
const madge = require('madge');

madge('path/to/app.js', {layout: 'fpd'})
    .then((res) => res.image('path/to/image.svg'))
});
```

You can see all available config options here: https://github.com/pahen/madge#configuration

**Comment by the-simian** [comment]
hey thanks, really appreciate the response
