### ISSUE TITLE
How am I suppose to pass requireJS config ? 

### ISSUE THREAD

**Issue by gs-akhan** [pahen/madge#109]
Hi, I am not finding any option that takes requireConfig as an Object. Am I missing something .?

```
require.config({ 
path : {
framework : "app/views"
}
})
```

Thanks

**Comment by pahen** [comment]
Hi!

It doesn't support passing in the config as an object, just a path to the config file to read. See `requireConfig` at https://github.com/pahen/madge#configuration. Or `--require-config` if you're using the CLI.
