### ISSUE TITLE
Finding circular dependencies is not very performant

### ISSUE THREAD

**Issue by TimHolzherr** [pahen/madge#110]
Hi

I`m using Madge and like it a lot :)
But unfortunately the feature to find circular dependencies is very slow.
I need to check approx 300 js files for circular dependencies and madge needs more than 20 minutes for that.
I use madge via the command line on windows: e.g. > Madge  --circular .\ProjectFolder
Strangely if I create a image of the same dependencies with madge --image graph.svg .\ProjectFolder it only takes one second and the image also highlights all circular dependencies.

**Comment by pahen** [comment]
That sounds very strange since it's the same code running the cyclic check for `--circular` and `--image`. Can you run madge with the `--debug` option to see what's going on?

**Comment by AHaberl** [comment]
I have a similar issue using the circular function in a unit test.
With version 0.6 it took only about 1500ms while it now takes up to 20s.

**Comment by pahen** [comment]
Is the project you're running it on available somewhere @AHaberl ? How are you invoking madge?
