### ISSUE TITLE
Support dependency injection

### ISSUE THREAD

**Issue by mohammadrafigh** [pahen/madge#111]
it would be great to see the dependency injection tree, specially useful for Angular apps.

**Comment by mrjoelkemp** [comment]
Thanks for contributing @mohammadrafigh. Can you provide an example of what the dependency injection tree would look like?

**Comment by mohammadrafigh** [comment]
sure, for instance when module 'A' (which may be an angular service) is injected into module 'B' (may be an angular controller) then it looks like this in angular 1.x form:

```
angular.module('myApp').controller('B', ['A', function() {
...
}
```
actually by dependency injection tree I mean showing the relations for injected dependencies other than importing them. it may be a tree or not, so this example would result B--->A.

**Comment by mrjoelkemp** [comment]
Thanks for clarifying! If the dependencies aren't imported, then this seems to be pretty specific to angular.

Is there anything in angular core that we could use to get a list of dependencies, and in the best case, the files that they map to on the filesystem?

**Comment by mohammadrafigh** [comment]
ummm dependency injection is actually a pattern to pass dependencies (specially singleton instances) into the modules and this pattern is defined in many frameworks out there (both on server and client side) but as I know it's really useful and common in Angular apps. in Angular 2 dependencies will inject using import attribute in a module or in a component you can see [this](https://angular.io/docs/ts/latest/guide/dependency-injection.html) example.

in Angular 1.x the pattern is like what I mentioned in previous comment but [this](http://stackoverflow.com/questions/19411502/angular-get-list-of-all-registered-services) may be helpful.

**Comment by mrjoelkemp** [comment]
I'm aware of DI not being specific to angular :) Angular handles DI in a specific way (as your links and the angular 1 DI docs suggest). 

> Using the inline array annotation (preferred)
> Using the $inject property annotation
> Implicitly from the function parameter names (has caveats)

Madge would have to have knowledge of those angular-specific DI annotations (for which Angular 2 is a bit more reasonable) and identify the definitions of those injectable modules. 

Yes, this falls in the realm of "dependency trees," however, it's a departure from more language-level dependency resolution. Not saying it shouldn't be included, but it sounds like a better fit in an angular-specific version of madge. 

I'm not an angular user, but this would definitely be cool. Thanks for suggesting.

**Comment by mohammadrafigh** [comment]
> I'm aware of DI not being specific to angular :)
sorry I misunderstood before :D 

if I found something I will post it here.

**Comment by pahen** [comment]
Thank's for contributing @mohammadrafigh but at the moment Angular dependency injection will not be supported by Madge. Since TypeScript and ES6 imports are used for Angular 2 I don't feel it's worth the time to support Angular 1 right now.
