### ISSUE TITLE
Can we give height/width for generated SVG?

### ISSUE THREAD

**Issue by gs-akhan** [pahen/madge#114]
Hi,
Currently the generated SVG is `width="2799pt" height="412pt"`. Is there a way to pass this dimensions?

Thanks

**Comment by pahen** [comment]
Hi,

One way to do this is by passing in another DPI than the default one used by graphviz. See http://web.mit.edu/spin_v4.2.5/share/graphviz/doc/html/info/attrs.html#d:dpi

You can specify this in madge by creating a `.madgerc` file like this:
```
{
	"graphVizOptions": {
		"G": {
			"dpi": 48.0
		}
	}
}
```
