### ISSUE TITLE
Webpack require.context

### ISSUE THREAD

**Issue by brianmhunt** [pahen/madge#117]
Thanks for the great work on madge.

It might be that I'm using it wrong, but it looks like it doesn't work with webpack's [`require.context`](https://webpack.github.io/docs/context.html) (it's basically a `glob`) so e.g.

```javascript
var context = require.context(".", true, /\.js$/)
context.keys().forEach(context)
```

loads all the modules with `/\.js$/` from the current directory (`"."`) and subdirectories (that's what the `true` specifies).

Just thought this might be of interest.  

Cheers :)

**Comment by brianmhunt** [comment]
... this is probably an upstream issue in node-dependency-tree, node-precinct, or enhanced-resolve ...

**Comment by pahen** [comment]
Thanks for reporting! I'm closing this for now since you created an issue in for it in node-precinct.
