### ISSUE TITLE
Webpack2 - alias

### ISSUE THREAD

**Issue by frck006** [pahen/madge#118]
Does madge work with webpack2 ?

I have this message:
 👍  cabinet Can't resolve '**lib/utils/Vars.js**' in 'C:\_TeamsRh\SmartMobile\TeamsRhNg\srhweb\webapps\ROOT\srh\smartmobile2\src' +2ms

**My script NPM:**
"graph3": "cls && madge --debug --webpackConfig build2/webpack.prod.debug.babel.js ./smartmobile2/src/components/index.js",

**index.js (after using babel):**
var _Vars = require("**lib/utils/Vars.js**");

**webpac.prod.debug.babel.js:**
( var dirAppli = _path2.default.resolve(__dirname, "..", process.env.dirAppli+"2");)
    resolve: {
        root: _path2.default.resolve(dirAppli, 'src'),
        alias: {
            appli: _path2.default.resolve(dirAppli, 'src'),
            **lib: _path2.default.resolve(__dirname, "..", "commons2", 'lib')**,
            icons: _path2.default.resolve(__dirname, "..", "icons"),
            img: _path2.default.resolve(__dirname, "..", "img")
        },
        extensions: [".js", ".json"]
    },
    resolveLoader: {
        moduleExtensions: ["-loader"],
        modules: [_path2.default.resolve(__dirname, "../node_modules")]
    },

Madge does not seem to use the alias "lib" or my config is not correct ?

**Comment by pahen** [comment]
Yes, it should work with webpack 2. I use madge with it. Can you try running it with the `--basedir` option and see if it helps? It would be easier to help you if I can see your entire webpack config too.

**Comment by frck006** [comment]
I've used "basedir" with several values, it doesn't change anything.
=> "basedir": path.resolve("smartmobile", "src"),
=> "basedir": path.resolve(__dirname, "smartmobile", "src"),
=> "basedir": path.resolve(__dirname, "..", "smartmobile", "src"),


My webpack config:

export default {
    context: dirAppli,
    entry: {
        // smartmob: Cette valeur est repris dans la variable [name] de output.filename.
        smartmob: [dirAppli+"/src/components/index.js"],
        // Toutes les librairies externes 
        vendors: ["jquery", "babel-polyfill", "font-awesome-webpack-2"]
    },

    output: {
        // Répertoire de la distribution.
        // On remonte dans le répertoire parent car le "webpack.base.js" est dans le répertoire "build".
        path: path.resolve(dirAppli, 'www'),
        // Nom du fichier contentant tous les js.
        // - hash                        : c'est suite de lettre déterminée à partir de ???
        // - name                        : Nom de la propriété de l'entrée: 'smartmob' ou 'vendor'.
        filename: "[name]-[hash:7].js",
        // Webpack préfixe les urls par le public path.
        // <img src="my-foo.png"> ==> <img src="/dist/img/my-foo.png">
        // Si le HMR (Hot Module Replacement) n'est pas connecté, vérifier la valeur de publiPath.
        // publicPath                     : "/www/",
    },

    resolve: {
        alias: {
            appli: path.resolve(dirAppli, 'src'),
            lib: path.resolve(__dirname, "..", "commons",'lib'),
            icons: path.resolve(__dirname, "..", "icons"),
            img: path.resolve(__dirname, "..", "img"),
        },
        extensions: [
            ".js",
            ".json"
        ],
    },

    resolveLoader: {
        moduleExtensions: ["-loader"],
        modules: [
            path.resolve(__dirname, "../node_modules")
        ]
    },


    module: {
        rules: [
            {
                test: /\.css$/,
                use: [
                    {
                        loader: "style-loader"
                    },
                    // importLoaders     : permet de configurer quel loader doit être appliqué
                    // aux ressources "@imported". 
                    // Dans ce cas, on applique "todo:je ne sais plus si c'est style ou postcss".
                    {
                        loader: "css-loader?importLoaders=1"
                    },
                    // CF postcss.config.js pour l'autoprefixer.
                    {
                        loader: "postcss-loader"
                    }
                ]
            }, {
                test: /\.less$/,
                use: [
                    {
                        loader: 'style-loader'
                    }, {
                        loader: 'css-loader',
                        options: {
                            importLoaders: 1
                        }
                    }, {
                        loader: 'less-loader',
                        options: {
                            strictMath: true,
                            noIeCompat: true
                        }
                    }
                ]
            }, {
                test: /\.js$/,
                enforce: "pre",
                use: [
                    {
                        // Pour babeliser.
                        loader: 'babel-loader'
                    },
                    // {
                    //  Pour l'EsLint.
                    //     loader: 'eslint-loader',
                    // },

                ],
                // include: /(FlexTable)/,
                exclude: /(node_modules|bower_components|build|vendors)/
            },
            // On a besoin de url-loader et file-loader.
            {
                test: /\.(png|ico|jpg|jpe?g|png|gif|svg|woff2?|eot|ttf)$/,
                use: [
                    {
                        loader: "url-loader",
                        options: {
                            // La taille du fichier < limit est converti en url-data.
                            // 10Ko = 10000
                            limit: 10000,
                            name: "[name]-[hash:7].[ext]"
                        }
                    }
                ]
            }, {
                test: /\.html$/,
                use: [
                    {
                        loader: 'html-loader'
                    }
                ]
            }
        ]
    },
    plugins: [

        // Ce plugin permet de créer un bundle ne contenant que le js correspondant
        // à l'"entry.vendor". Cela permet de séparer le code qui ne change pas
        // beaucoup avec le code métier qui, lui, peut changer souvent. Améliore le cache.
        // Mais cela permet également de ne pas charger tous les js, notamment ceux
        // qui ne sont pas utilisés au démarrage de l'application.
        // L'option 'manifest' est necessaire pour ne pas invalider le cache du fait que l'on
        // ajoute un hash sur le nom du bundle 'vendor'.
        // Laisser ce plugin en 1er car il est retiré dans la conf karma.
        new webpack.optimize.CommonsChunkPlugin({
            name: ['vendors', 'manifest']
        }),

        // Crée le fichier "index.html" dans le répertoire "output.path"
        // en utilisant le template "index.html". Dis comme ca, ce n'est pas fou fou.
        // Mais si on ajoute un hash dans le nom fichier "output.filename", et bien,
        // le plugin renseigne correctement la balise <script> dans le fichier
        // "index.html" avec le hash.
        new HtmlWebpackPlugin({
            //title: 'Custom template', template: 'src/index.html',
            title: 'Custom template', template: dirAppli + '/src/index.html',
            // hash                      :true
        }),

        // Pour ajouter des options sur les loaders.
        new webpack.LoaderOptionsPlugin({
            options: {
                eslint: {
                    // Ce formateur indique et montre la ligne à corriger.
                    formatter: require('eslint-friendly-formatter')
                }
            }
        }),

        // Définit des variables globales qui peuvent être utilisées dans les js.
        new webpack.DefinePlugin({
            // __DEV__: JSON.stringify(JSON.parse(process.env.BUILD_DEV || 'true')),
            // __PROD__: JSON.stringify(JSON.parse(process.env.BUILD_PROD || 'false')),
            __URL_SMARTRH__: JSON.stringify(process.env.urlsmartrh || 'false'),
        }),

        // Permet de spécifier une variable pour un module.
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            // Pour angulare            :
            'window.jQuery': 'jquery'
        }),
    ]
