### ISSUE TITLE
Not detecting circular dependence based on NODE_PATH

### ISSUE THREAD

**Issue by sseidametov** [pahen/madge#120]
I have issue in my app and found this nice package, that would help me to resolve issue. But I'm using `NODE_PATH=./` in my app an call dependencies by app root. I've built a test app to check if it is possible to ignore like that dependencies:

```js
// a.js
let b = require('test/b.js');

console.log(b);
```
```js
// b.js
let a = require('test/a.js');

console.log(a);
```
```
$ NODE_PATH=./ madge --circular test/a.js
Processed 1 file (309ms) (1 warning)

✔ No circular dependency found!
```

Looks, it ignore `NODE_PATH` param.

PS: It is also not building graph based on it. Seems, issue root is hidden here.

**Comment by pahen** [comment]
I see that you got "1 warning", Try to run madge with `--warning`and see what it says.

**Comment by sseidametov** [comment]
```
 madge --circular --warning test/a.js
Processed 1 file (378ms) (1 warning)

✔ No circular dependency found!

✖ Skipped 1 file

test/b.js
```

**Comment by pahen** [comment]
Try `madge --circular --warning --basedir . test/a.js` and see if it helps.

**Comment by sseidametov** [comment]
Yes, it works. Thank you. (but a bit unexpected)

**Comment by pahen** [comment]
Good! `--basedir` is basicially the same as using `NODE_PATH`.
