### ISSUE TITLE
Typescript circular dependency found in node_module package

### ISSUE THREAD

**Issue by neurosnap** [pahen/madge#125]
I love this project so thank you for continuing to maintain it!  I'm building a Typescript project and want to check for circular dependencies.  It looks like a package I'm using `redux-saga` has a circular dependency.  The way I'm getting around it now is `excludeRegExp` but I'm wondering why this is an issue?

```bash
> madge --circular src/delivery/web/index.ts

Processed 18 files (1.1s) (7 warnings)

✖ Found 3 circular dependencies!

1) ../../../../redux-saga/effects.d.ts > ../../../../redux-saga/index.d.ts
2) ../../../../redux-saga/effects.d.ts > ../../../../redux-saga/index.d.ts > ../../../../redux-saga/utils.d.ts
3) ../../../../redux-saga/index.d.ts > ../../../../redux-saga/utils.d.ts
```

**Comment by pahen** [comment]
Nice that you like it! I'm actually not using redux-saga or Typescript so I think you have to ask the redux-saga team if it's a real issue.
