### ISSUE TITLE
Import circle not detected with index file exporting everything

### ISSUE THREAD

**Issue by justyun** [pahen/madge#126]
Firstly thank you for having this project and I absolutely love it. It saves us tons of time figuring out weird issues.

I met a case where there are two folders, say utils and constants:

under utils there are index.js and a.js (where index.js has export * from a)
under constants there are index.js and b.js (where index.js has export * from b)
a.js has import { xx } from constants, and b.js has import { yy } from utils

such circular import causes some issues in our project, but not detected by madge. 
alias is used in our project but I don't think that affects the result.

Thanks.

**Comment by Tymek** [comment]
I couldn't reproduce it in https://repl.it/@Tym3k/githubcompahenmadgeissues126. Did I do something different? Would you be able to provide an example?
