### ISSUE TITLE
Question: Is there any way to list the deep dependents of a module?

### ISSUE THREAD

**Issue by mruzekw** [pahen/madge#131]
Currently it looks like `--depends` only shows direct dependents. Is there any way to list the deep dependents of a module?

**Comment by mrjoelkemp** [comment]
Thanks for the question @mruzekw. I'll answer here even for https://github.com/dependents/node-dependents/issues/80. 

What do you mean by deep dependents? What would you want the output to be?

**Comment by shusson** [comment]
Any reason this was closed? Is this something that is possible with madge?
