### ISSUE TITLE
--depends Not Working

### ISSUE THREAD

**Issue by taicho** [pahen/madge#133]
I just installed latest madge today. I've tried warning and debug and cannot get any dependents to show up when using depends. I've tried using a simple setup and no matter what madge processes all the files successfully but does not show any output.

Example directory structure:

- server
  - lib
    - someFile.js
  - anotherDirectory
    - fileRequiringSomeFile.js

running `madge --depends ./someFile.js ./` or `madge --depends absolutePath/to/someFile.js absolutePathToRootDirectory` or any mix of the above scans successfully but shows no results. Am I doing something wrong? When running with --debug I can even see it traversing and showing the absolute paths and even see the file(s) but still at the end no errors and no results.

Thoughts?

**Comment by pahen** [comment]
Hi,

The path given to `--depends` should match the path outputted by `--summary`

**Comment by pahen** [comment]
So `madge --depends someFile.js` or `madge --depends relativePath/someFile.js`

**Comment by taicho** [comment]
@pahen Thanks for the reply and my apologies for such a late one. I did indeed end up figuring it but I pulled out a lot of hairs in between that! :-D
