### ISSUE TITLE
CLI does not honor graphVizOptions when outputting dot format

### ISSUE THREAD

**Issue by MarcelloPerathoner** [pahen/madge#138]
The CLI honors graphVizOptions only with --image but not with --dot.

**Comment by Mnuzz** [comment]
Seems the dot output format really doesn't look at the config at all, so the graphviz graph looks nearly unreadable. It would be really great to have this, as a .dot file can potentially be navigated more easily with a native graph viewer, while an svg file is effectively unreadable with large graphs (which let's be honest, if you need a tool like madge then your dependencies are going to be large and complex). 

The code that outputs the dot format is here. Additionally, it appears to affect the JS API as well as the CLI. https://github.com/pahen/madge/blob/v3.4.4/lib/graph.js#L142-L159

Anyone else think this might be useful?

**Comment by pahen** [comment]
This is fixed now
