### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by sveinburne** [pahen/madge#142]
After a huge headache over circular dependency resulting in undefined imports, I found your tool which, honestly, saves my day. Therefore I want to send you love and mental free hugs.
So a big thanks for your super easy to use and yet powerful tool.

**Comment by pahen** [comment]
Thanks! Makes my day that it saves your day! I maybe use your text for a testimonial :) Have a nice day!

**Comment by sveinburne** [comment]
You're welcome to do it
Have a good day too :-)
Cheers

**Comment by kiranjd** [comment]
It has been two days and I'm still resolving circular dependencies that had been accumulated over past 4 years. Madge has helped a lot. Thank you!
