### ISSUE TITLE
Can't see beyond first level dependencies

### ISSUE THREAD

**Issue by nicolocarpignoli** [pahen/madge#145]
Hi. I get only one level of dependencies on my project.
Say, I have a file name `mediaParent` that has:

```
import '@myrepo/media-child1';
import '@myrepo/media-child2';
```

On the generated graph image, I only see `mediaParent1` that is dependent from `media-child1` and `media-child1` (with option `--includeNpm`).
What If I want to see dependencies of `media-child1` and `media-child2`? 
I mislead something or this has to be the exact purpose of this library? 

Thanks in advance

**Comment by pahen** [comment]
Yes, this is intentional. It was not designed for doing deep a NPM dependency overview. There's other tools for that.

**Comment by nicolocarpignoli** [comment]
Thanks. Can you suggest me at least one of these tools? It would be great.

**Comment by pahen** [comment]
Here's at least on version you can you use online: http://npm.broofa.com/?q=madge

**Comment by nicolocarpignoli** [comment]
@pahen  Thanks, but this works with published modules. What about private ones? I'd like something that works locally

**Comment by nicolocarpignoli** [comment]
No problem on it :)

Just say, it would be nice if on the readme of `madge` it's clear that this doesn't work with NPM dependencies, which are pretty used nowadays  :)

`Will traverse child dependencies automatically`. I suggest to specify this limitation. I have a feel that many people by reading the readme like me has mislead that. Anyways, great library and great job
