### ISSUE TITLE
RFE: Support tilde alias in imports

### ISSUE THREAD

**Issue by joebowbeer** [pahen/madge#148]
madge is ignoring imports of the form:

```
// With Babel-Root-Importer
import SomeExample from '~/some/example.js';
const OtherExample = require('~/other/example.js');
```

that are enabled by the [babel-plugin-root-importer](https://github.com/entwicklerstube/babel-plugin-root-import) plugin.

Imports of this form can also be configured using webpack `resolve.alias`, which madge does not support either.

Related bug: #99 

Is there a workaround for this? If madge supported webpack resolve.alias, I could create a dummy webpack config as a workaround...

**Comment by pahen** [comment]
Are you passing in the webpack config to Madge?

**Comment by joebowbeer** [comment]
I might pass in a dummy webpack config with a resolve.alias for this purpose, but AFAICT madge does not support that, nor does it support the newer webpack 3.0 attributes, right?

**Comment by pahen** [comment]
Madge is using `dependency-tree` which is using `node-filing-cabinet` which I believe should have support for `resolve.alias`. See the test https://github.com/dependents/node-filing-cabinet/blob/master/test/test.js#L575

**Comment by joebowbeer** [comment]
I'll verify this soon. Thanks.
