### ISSUE TITLE
-l is not working as alias for layout option

### ISSUE THREAD

**Issue by joebowbeer** [pahen/madge#150]
The following command with `--layout` makes a circle:

```
echo '{ "a": ["b"], "b": ["c"], "c": ["a"] }' | madge --stdin --layout circo -i circo.svg
```

but the same command except with `-l` actually uses default layout:

```
echo '{ "a": ["b"], "b": ["c"], "c": ["a"] }' | madge --stdin -l circo -i circonot.svg
```

These results are from bash shell running on macOS 10.13.3

**Comment by pahen** [comment]
Thanks for reporting! Should be fixed now in v3.0.1
