### ISSUE TITLE
CI compliant output

### ISSUE THREAD

**Issue by MichaelBitard** [pahen/madge#156]
First, thanks for this project, it helped us find some really tricky and annoying circular dependencies!

We'd like to help improving madge.

Our CI (Jenkins) output every processed file in a very unreadable way:

Just a little truncated example: 
```
> madge --circular ./js

⠋ api/apis.js⠙ api/auth/auth.js⠹ api/json/json.types.js⠸ api/problems/problems.js⠼ infra/i18n.js⠴ api/sitecc/sitecc.js⠦ store/site/siteInfo.types.js⠧ api/sitecc/sitecc.types.js⠇ store/lines/creation/lineCreation.types.js⠏ store/lines/lineDefs/lineDefs.types.js⠋ api/browser/browser.js⠙ api/webrtc/webrtcApi.js⠹
```
Can we add an option to output in a more CI-friendly way? (For example when variable CI=true)

**Comment by pahen** [comment]
The you should be able to run `madge --circular --no-color --no-progress ./js` and get clean output.

**Comment by matthias-ccri** [comment]
For posterity --- the option is `--no-spinner`, not `--no-progress`

**Comment by pahen** [comment]
> For posterity --- the option is `--no-spinner`, not `--no-progress`

Thanks! :)
