### ISSUE TITLE
How to view dependencies between node_modules?

### ISSUE THREAD

**Issue by qwertie** [pahen/madge#160]
This didn't show as much info as I was hoping for....
~~~
C:\Dev\climate-app>madge .
Processed 2 files (893ms)

app/app.js
server.js
~~~

What I want to do is understand dependencies between packages in node_modules. It seems I can't:
~~~
C:\Dev\climate-app>madge node_modules
Processed 0 files (723ms)
~~~

**EDIT**: I just found out npm has a built-in way to show a dependency tree of modules: `npm list`.

I'm also wondering: in a large project, can you suppress transitive dependencies? i.e. if there is a path X->Y->Z, and another path X->Z, suppress display of X->Z?

**Comment by joebowbeer** [comment]
For grouping paths I wrote a transformer that might be a good starting point:

https://github.com/joebowbeer/repdeps

**Comment by melissachang** [comment]
I have the same question as @qwertie . I suspect I have a circular dependency, but madge doesn't print any `node_modules` dependencies:
```
~/data-explorer (mc/histogram-facet): madge ui/src/components/facets/HistogramFacet.js 
Processed 2 files (338ms) (8 warnings)

HistogramFacet.css
HistogramFacet.js
  HistogramFacet.css
```

**Comment by pahen** [comment]
Have you tried the —include-npm option @mellisachang? It can be terribly slow though.

**Comment by melissachang** [comment]
Yes, that didn't help.
```
~/data-explorer (mc/histogram-facet): madge --include-npm ui/src/components/facets/HistogramFacet.js 
Processed 2 files (336ms) (8 warnings)

HistogramFacet.css
HistogramFacet.js
  ../../../node_modules/@material-ui/core/styles/index.js
  ../../../node_modules/react/index.js
  HistogramFacet.css
```

`HistogramFacet.js` includes:
```
import React, { Component } from "react";
import { canvas } from "vega-canvas";
import { Handler } from "vega-tooltip";
import * as vl from "vega-lite";
import * as vega from "vega-lib";
import Vega from "react-vega";
import { withStyles } from "@material-ui/core/styles";

import "./HistogramFacet.css";
import * as Style from "libs/style";
import colors from "libs/colors";
import FacetHeader from "components/facets/FacetHeader";
```
Chrome Developer Tools shows a bunch of things are imported:
![1](https://user-images.githubusercontent.com/10929390/54766126-fbf8dd80-4bb7-11e9-9c89-18a38e565801.png)

Context is, I think there's a circular dependency somewhere and I was hoping madge could find it. (I'm using create-react-app so I can't use [circular-dependency-plugin](https://www.npmjs.com/package/circular-dependency-plugin).)
