### ISSUE TITLE
custom config.filter function does not override inbuilt filter

### ISSUE THREAD

**Issue by imvetri** [pahen/madge#166]
Hi,

I am using madge for generating dependency graph for a commonJS codebase. I used the config to pass custom configuration setting for madge but what I found is that there is a filter function at [madge/tree.js](https://github.com/pahen/madge/blob/master/lib/tree.js#L122) which is overriding my config.filter function.

If this is something that will be useful for madge I am open to make code changes.

Thanks!

**Comment by pahen** [comment]
You should use `config.dependencyFilter` for that. See https://github.com/pahen/madge#configuration
