### ISSUE TITLE
Treat meteor packages as npm packages

### ISSUE THREAD

**Issue by SimonSimCity** [pahen/madge#168]
I'm using this tool here on a project which is based on Meteor.

Meteor has it's own package-management which is compliant to the npm-notation, but cannot be found in the NPM folder - which looks like following:

```
import { ValidatedMethod } from 'meteor/mdg:validated-method';
```

The import stated above imports the module https://atmospherejs.com/mdg/validated-method which has to be installed in your project. The text `meteor/` is used as a keyword here to let the meteor-internal NPM fork search for a package in the meteor package list.

I'd like this project to include these packages in the generated output when adding `--include-npm` or to add another option to allow it.

**Comment by pahen** [comment]
I'm afraid this is out of the scope for Madge.

**Comment by SimonSimCity** [comment]
Could I then get an option that would not verify that a package actually exists in the `node_modules` folder bug just lists it in the output ..? I would also be OK if this would then be an additional `--include-all-imports` or something like this. In my opinion this is within the scope of this package and would even add to other eco-systems where they have their additional package-management-system, like Meteor has.

**Comment by pahen** [comment]
I'm open for a PR to fix this but nothing I'll be working on. The purpose of Madge is to analyze your own packages and not NPM modules.
