### ISSUE TITLE
Getting Circural dependancies in code from all files (*.ts) from folder 

### ISSUE THREAD

**Issue by Lordsklilen** [pahen/madge#175]
I have about 4000 files coded in typescript and I want to get all the circular dependancies of all files. I have tried to do it one by one but it is very slow(about 20 minutes each iteration). I need to do it frequently so i try to make it faster. Is it possible to run it via code and don't iterate through all files? I have something like that now:
` for (let file of finalProject.getSourceFiles()) {
                let cycles = await madge(file.getFilePath());
                if (cycles.circular().length > 0) {
                    for (let cycle of cycles.circular()) {`

It works but it is very slow. Any tips or advices?

**Comment by pahen** [comment]
Do you have one entry point for you project/app?
