### ISSUE TITLE
Use one file as entry (instead of a directory)

### ISSUE THREAD

**Issue by tiye** [pahen/madge#19]
In a senario like RequireJS, it's more like there's only one entry in the HTML, the optimizer of RequireJS analyses the main file, then all dependencies are figured out, instead of scanning a whole directory to figure out the depencies.

I can't find a parameter for scanning file like that? How about it, can we add that?

**Comment by dizzib** [comment]
:+1:

I'm using https://github.com/substack/node-browserify e.g:

    $ browserify main.js > bundle.js

Since [my browserify FR](https://github.com/substack/node-browserify/issues/961) got rejected I'd also like to be able to detect circular deps from a single entry point:

    $ madge -c main.js

Similarly on the api:

    madge('./main.js');

Cheers!

**Comment by skyl** [comment]
It looks like these options were removed at some point. Is there a way to run against an optimized file in the recent versions? I have 3.0.1 at the moment.
