### ISSUE TITLE
not detecting circular dependencies with require-directory

### ISSUE THREAD

**Issue by oprogramador** [pahen/madge#192]
OS: Mac OS X 10.12.6
Node.js: 10.15.0
npm: 6.4.1
madge: 3.3.0
require-directory: 2.1.1

When I use `madge` with [require-directory](https://github.com/troygoode/node-require-directory), it doesn't detect circular dependencies.

Example repo: https://github.com/oprogramador/madge-not-working
See this build https://travis-ci.org/oprogramador/madge-not-working/builds/473994109

**Comment by namnm** [comment]
Hi guys, any news?

**Comment by pahen** [comment]
Sorry, we're not going to support. This tool can only compute dependencies by using static analysis and `require-directory` breaks that.
