### ISSUE TITLE
[Question] is report unused files feature possible?

### ISSUE THREAD

**Issue by RusinovAnton** [pahen/madge#195]
Hi. GJ on a great tool.
I've just built a "graph.svg" for my project and found a file that had no relations at all. 
It seems like it should be possible to have a feature to report unused files, for example:

```
madge --unused src/

List of unused files in src/
- components/LegacyComponent.js
- components/styles/OldBrokeUnused.css
```

**Comment by RusinovAnton** [comment]
yeah. there is an "orphans" method

**Comment by pahen** [comment]
Yes, --orphans was probably a bad name for that feature :)

**Comment by RusinovAnton** [comment]
I think orphans is fine. I missed that because I was looking into CLI docs and there is no info about it there, thats why I opened https://github.com/pahen/madge/pull/196
