### ISSUE TITLE
Go threw package.json instead of index.js

### ISSUE THREAD

**Issue by Madebymaurice** [pahen/madge#198]
Hello,

Thanks for your great work, I would like to use Madge for a particular things.
I have too many packages in node_modules and many of them are import multiple time by different scene.
We use webpack for create bundle js by scene and common bundle. And we would like to analyze our node_modules for made a better dispatch in our bundle.
So madge go threw the tree and for files in node_modules returns the `index.js` in the `build` folder.
As Madge is already able to go threw the full tree, would you think if it's possible to return the `dependencies` in `package.json` instead of index.js ?

Thanks for your help

**Comment by pahen** [comment]
Sorry, I think this is out of the scope for Madge. Closing this for now.
