### ISSUE TITLE
Orphans() don't work with requireConfig

### ISSUE THREAD

**Issue by mmoo** [pahen/madge#199]
As soon as any requireConfig is applied finding orphans stops working. No matter if it's just an empty file or a valid config.
Instead of a list of modules that no one is depending on a list of all modules is returned.
[orphans_with_require_config_test_patch.txt](https://github.com/pahen/madge/files/2797341/orphans_with_require_config_test_patch.txt)

**Comment by pahen** [comment]
Seems to work for me. Added a test here: https://github.com/pahen/madge/commit/ab73af86e24a6a57192eb70164bdf49712455d8d

Open this if you still believe it's not working.
