### ISSUE TITLE
"See it in action" recording has been archived

### ISSUE THREAD

**Issue by reduckted** [pahen/madge#206]
The screen recording in the "See it in action" section of the readme is unavailable.

![image](https://user-images.githubusercontent.com/10321525/52762122-e563e180-3061-11e9-8852-ce666f2e7d65.png)

Clicking the link takes me to a page that says:

> ## This recording has been archived
> All unclaimed recordings (the ones not linked to any user account) are automatically archived 7 days after upload.

**Comment by pahen** [comment]
Thanks for reporting. Fixed now :)
