### ISSUE TITLE
Add support for .mjs file type recommended by Google

### ISSUE THREAD

**Issue by Lucent** [pahen/madge#209]
On [Google's Web Fundamentals site](https://developers.google.com/web/fundamentals/primers/modules), they recommend using the .mjs extension for modules:

> A note on file extensions
> You may have noticed we’re using the .mjs file extension for modules. On the Web, the file extension doesn’t really matter, as long as the file is served with the JavaScript MIME type text/javascript. The browser knows it’s a module because of the type attribute on the script element.
> Still, we recommend using the .mjs extension for modules, for two reasons: ...

However if madge is pointed at .mjs files referencing other files, it can't resolve the dependencies.

**Comment by pahen** [comment]
I rather wait with adding support for this until the support for this is non-experimental in Node.JS. Closing this for now.
