### ISSUE TITLE
How to recognize dependency more than one level up in a root? 

### ISSUE THREAD

**Issue by sinapsist** [pahen/madge#210]
Hello everyone,

I need some help with understanding Madge. I tried to use on a project with some dependencies
There is a part of my import of my ComponentSample.tsx.

import { Base } from '../../Common/Base';
import { styles } from './ComponentSample.css';
import { ChildComponent } from '../ChildComponent';

And on my dependency graph I can see that: 
ComponentSample.tsx -> ComponentSample.css
ComponentSample.tsx -> ChildComponent.ts
But I cannot see that my component depends on Common Base.

Why it is not showing up as a dependency? What should I do to fix it?

Thank you so much!

**Comment by pahen** [comment]
What does the command you're running look like?

**Comment by PabloLION** [comment]
Closed for inactivity
