### ISSUE TITLE
Provide configuration file schema

### ISSUE THREAD

**Issue by anion155** [pahen/madge#212]
Please, create github-hosted schema file for [json$schema](https://json-schema.org/understanding-json-schema/reference/schema.html) support. Some ide supports `$schema` parameter and provides intellisense for json files ([VSCode](https://code.visualstudio.com/docs/languages/json#_mapping-in-the-json), [WebStorm](https://www.jetbrains.com/help/webstorm/2016.1/json-schema.html?page=1)). It would be very convenient.

**Comment by pahen** [comment]
What exactly do you need this for?

**Comment by anion155** [comment]
IDE support only. It's really convenient to have IDE's support for config files, with builtin documentations. But there is no all-in-one repository for json-schemas like DefinetlyTyped for ts typings. So I'm asking here.

**Comment by anion155** [comment]
Sorry. Found out this rep https://github.com/schemastore/schemastore/

**Comment by Nick2bad4u** [comment]
Looks like this was never done or submitted to the other repo.
