### ISSUE TITLE
Strict mode in Babel + Jest causes graphviz files to throw error

### ISSUE THREAD

**Issue by cyrus-za** [pahen/madge#214]
I get an error when running a test in [Jest 24]() with [Babel 7]()
`Legacy octal literals are not allowed in strict mode`

```js
 FAIL  src/misc.test.ts
  ● Test suite failed to run

    SyntaxError: /node_modules/graphviz/node_modules/temp/lib/temp.js: Legacy octal literals are not allowed in strict mode (101:20)

       99 | var mkdir = function(affixes, callback) {
      100 |   var dirPath = generateName(affixes, 'd-');
    > 101 |   fs.mkdir(dirPath, 0700, function(err) {
          |                     ^
      102 |     if (!err) {
      103 |       deleteDirOnExit(dirPath);
      104 |     }

      at Object.state (node_modules/@babel/parser/lib/index.js:6293:16)

```

As you can see above, the error occurs in `/node_modules/graphviz/node_modules/temp/lib/temp.js`

[graphviz](https://www.graphviz.org/) is used by `madge` as per 
```log
yarn why graphviz
yarn why v1.17.0
warning ../../package.json: No license field
[1/4] 🤔  Why do we have the module "graphviz"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "graphviz@0.0.8"
info Reasons this module exists
   - "madge" depends on it
   - Hoisted from "madge#graphviz"
info Disk size without dependencies: "528KB"
info Disk size with unique dependencies: "572KB"
info Disk size with transitive dependencies: "900KB"
info Number of shared dependencies: 8
✨  Done in 0.89s.
```

I did not install the optional graphviz as per the madge readme as I do not require visual images. I simply wrote a unit test to test for circular dependencies.

**Comment by pahen** [comment]
Why are Jest parsing files under `node_modules/graphviz` ? You must have done something wrong.

**Comment by cyrus-za** [comment]
Can't get it working inside my `JEST` but I switched to using `shelljs` and execute the command line rather than requiring the module and it works fine. It seems to have something to do with the default tsconfig that `jest` executes when initiated by `react-scripts`

Running it with just ts-node also breaks but using a custom ts-config with commonjs works fine. Unfortunately `react-scripts` overwrites the ts-config on each build and there is no way to specify --project to tell `jest` how to execute this as jest.config.js is internal inside `create-react-app`

That being said, this issue can be closed as it is not related to madge or graphviz

**Comment by DanTrofimov** [comment]
Sup 👋

Still getting the same logs:
```js
SyntaxError: /node_modules/graphviz/node_modules/temp/lib/temp.js:
Legacy octal literals are not allowed in strict mode (101:20)

   99 | var mkdir = function(affixes, callback) {
  100 |   var dirPath = generateName(affixes, 'd-');
> 101 |   fs.mkdir(dirPath, 0700, function(err) {
      |                     ^
  102 |     if (!err) {
  103 |       deleteDirOnExit(dirPath);
  104 |     }
```

In the `jest.config` I have configured `transformIgnorePatterns` to not parse the `node_modules/graphviz`, but I've got the same issue.

So, bumping `temp` to the `0.9.0` version in the `package.json` helped me:
```json
"resolutions": {
  "madge/graphviz/temp": "~0.9.0"
},
```

Now it works fine. @pahen, what do you think about adding something similar to the `madge`, untill `graphviz` bump the `temp` version? 

Thanks ✨
