### ISSUE TITLE
Typescript ignore "import types"

### ISSUE THREAD

**Issue by samfrances** [pahen/madge#217]
The `madge --circular` command appears to have changed its behavior, and is now picking up ["type only imports"](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#import-types) in Typescript. An option to disable this would be useful (i.e. to not count type-only imports when looking for circular dependencies)

**Comment by samfrances** [comment]
The issue appears to be an upgrade of https://github.com/pahen/detective-typescript from version `5.2.0` to version `5.4.0`.

Adding the following to my `package.json` appears to solve it, but it's not ideal:
```
"resolutions": {
    "madge/dependency-tree/precinct/detective-typescript": "5.2.0"
  },
```

**Comment by samfrances** [comment]
Specifically, this commit to detective-typescript may be the issue:

https://github.com/pahen/detective-typescript/commit/8bbf903ced23a82ed53f7ea6e6a90b08434af8ff

Of course, including type-only imports is a perfectly reasonable thing to do, but I think it's also perfectly reasonable to want to exclude them.

**Comment by pahen** [comment]
I'm not using TypeScript myself so can you give me some use case when circular dependencies is   ok when importing types?

**Comment by samfrances** [comment]
The use case I'm getting at is one where the runtime dependencies **aren't** circular, but the type-only import makes it look like they are.

I'm not sure if I'm explaining this well, but the argument is the same as that made in https://github.com/pahen/madge/issues/174, but for Typescript rather than flow.

**Comment by pahen** [comment]
Ok, thanks. So I suppose you want something like https://github.com/dependents/node-detective-es6/pull/13 but for TypeScript then?

**Comment by samfrances** [comment]
Yes, that's exactly it! :smile: 

If it helps, I'm happy to attempt a PR for the change in https://github.com/pahen/detective-typescript, where I think I can see what would need to be done (adding an option to the `detective()` function).

I haven't worked out how to thread that through in https://github.com/pahen/madge though...

**Comment by samfrances** [comment]
Ok, I have made a PR: https://github.com/pahen/detective-typescript/pull/20
Let me know if there are any things you don't like, want changed etc.

**Comment by pahen** [comment]
Can you do a fresh install of madge and put this in your `.madgerc` and see if it works for you now?

```json
{
	"detectiveOptions": {
		"ts": {
			"skipTypeImports": true
		}
	}
}
```

**Comment by samfrances** [comment]
That works! :smile:
Thanks so much @pahen! That's the first time I've seen an open source issue resolved in an afternoon. Fantastic!

**Comment by pahen** [comment]
Sweet! 🎉And thanks for your contribution! I've added a note about it in the FAQ: https://github.com/pahen/madge/tree/master/#how-to-ignore-import-in-type-annotations-in-typescript :)
