### ISSUE TITLE
How to specify excludeRegExp on the command line

### ISSUE THREAD

**Issue by JanFellner** [pahen/madge#222]
Is it a bug or just not the proper command line parameters?

I try to skip "**.d.ts**" file while searching for circular dependencies because those files are generated while compiling and the checking of the circular dependencies is a dedicated operation without compilation.

Thus i use:
`npx madge --circular --extensions ts --excludeRegExp ["\.d\.ts$"] ./`
(i tried also different notations like the javascript approach, without array notation...)

I then receive the following error:
```
 TypeError: excludeRegExp.map is not a function
    at Tree.exclude (X:\dev\UCConference\client\node_modules\madge\lib\tree.js:226:36)
    at Tree.generateTree (X:\dev\UCConference\client\node_modules\madge\lib\tree.js:153:16)
```

Is there a sample on how to use the excludeRegExp switch?

**Comment by pahen** [comment]
Hi! See https://github.com/pahen/madge#examples-1 on how to do this.

**Comment by JanFellner** [comment]
There is no sample for this parameter and the documentation is not really helpful...

**Comment by pahen** [comment]
This doesn't work for you? `madge --circular --extensions ts --exclude '\.d\.ts$' ./`

**Comment by JanFellner** [comment]
this is at least not causing the error :) but not filtering the .d.ts files :\

**Comment by pahen** [comment]
Hmm, that's weird . It should work.

**Comment by JanFellner** [comment]
So there are actually two issues: The doc seems also to be outdated cause you mention to use property **exclude** where the doc points out to use **excludeRegExp** ?!

**Comment by pahen** [comment]
No, you're mixing things up.

`excludeRegExp ` in an API option to be used in code. See https://github.com/pahen/madge#api

`exclude` is and CLI option to be used from the terminal. See https://github.com/pahen/madge#cli

**Comment by JanFellner** [comment]
gotcha,

- npx madge --circular --extensions ts --exclude '\.d\.ts$' ./
is NOT working in vscode on win

- npx madge --circular --extensions ts --exclude "\.d\.ts$" ./
is WORKING in vscode on win

thanks
