### ISSUE TITLE
Creating graph of only circular deps?

### ISSUE THREAD

**Issue by gaspardip** [pahen/madge#223]
It seems that you cannot create a graph that consists only of circular deps by any means, tried both a single command and using pipes, but no luck.

The commands I ran:

`madge --circular --dot ./src | dot -T svg > graph.svg`
`madge --circular --json ./src | madge --stdin --image svg.svg`
`madge --circular ./src --image svg.svg`

Is there any way to achieve this?

**Comment by pahen** [comment]
No, it's not possible to combine `--circular` with other output options but I suppose it would be pretty easy to fix.

**Comment by gaspardip** [comment]
I can take a look if you guide me a bit
