### ISSUE TITLE
(Typescript) Type-only imports shown as circular depedencies

### ISSUE THREAD

**Issue by raijinsetsu** [pahen/madge#225]
We typically deal with cyclic dependencies in Typescript by importing the types at the start of the file but then importing the code later (ie. "import('module').then((mod) => mod.function...)").

When importing types, they are still reported on cyclic dependencies, which is incorrect.

Is the only solution to this to run madge against the JS output instead of the TS input?

**Comment by pahen** [comment]
Try https://github.com/pahen/madge#how-to-ignore-import-in-type-annotations-in-typescript

**Comment by raijinsetsu** [comment]
Wow... Don't know how I missed that. Thanks!
