### ISSUE TITLE
can't create img

### ISSUE THREAD

**Issue by zhangenming** [pahen/madge#227]
but it create text list normal
and i get https://graphviz.gitlab.io/download/ here
win10 thanks

**Comment by pahen** [comment]
Do you get any error?

**Comment by zhangenming** [comment]
![企业微信截图_15713796397369](https://user-images.githubusercontent.com/21235555/67070368-76232c00-f1b2-11e9-9887-cc6e9f1ea537.png)

and I install graphviz-2.38.msi
