### ISSUE TITLE
a question about webpackConfig

### ISSUE THREAD

**Issue by sufengyong** [pahen/madge#228]
hi,thanks for your madge.
I have a question about webpackConfig.
I passed a path of a webpackConfig file but it doesn't work.
![image](https://user-images.githubusercontent.com/22764370/68087167-ff628000-fe8d-11e9-902c-8b686371bbb5.png)
![image](https://user-images.githubusercontent.com/22764370/68087179-1e611200-fe8e-11e9-8c65-260c90d98497.png)
![image](https://user-images.githubusercontent.com/22764370/68087188-3042b500-fe8e-11e9-912e-86687ac25049.png)

The result does not show that main.js is dependent on test.js

**Comment by pahen** [comment]
try `--webpack-config` instead of `--webpackConfig` and see if it works better

**Comment by sangfor-uedc** [comment]
I tried but it didn't work. Can you divine the cause? The demo is very simple, it's just what the picture shows. Is there any configuration item that madge needs to pay attention to?

**Comment by mrjoelkemp** [comment]
Try turning on the es6.mixedImports. Curious if it would work if you
changed the require to an import.

**Comment by sufengyong** [comment]
For project reasons, we use require consistently. Another problem is that when I import files using both require and import, madge's analysis shows only files that are imported in one of the two ways. Are these two problems bugs?

**Comment by sufengyong** [comment]
If I import the file using import, madge's analysis shows that it is correct.

**Comment by pahen** [comment]
Try this https://github.com/pahen/madge#using-both-commonjs-and-es6-imports-in-same-file @sufengyong

**Comment by sufengyong** [comment]
With mixedImports I can import files using both require and import. But for the first question about passing in webpack configuration files using require without identifying files that use the alias path, do you have a solution？

**Comment by sufengyong** [comment]
I'm sorry! I found the cause of the mistake. When I upload the webpack configuration file, allias in the webpack configuration file should use a string instead of the original path.resolve(XXX).

**Comment by goldsand1100** [comment]
> I'm sorry! I found the cause of the mistake. When I upload the webpack configuration file, allias in the webpack configuration file should use a string instead of the original path.resolve(XXX).

hi, i have this question also.   can i see your code ?
