### ISSUE TITLE
Ignoring runtime requires?

### ISSUE THREAD

**Issue by pcorey** [pahen/madge#230]
Imagine I have two files, `a.js`:

```js
require('./b.js');
```

And `b.js`:

```js
function foo() {
  requite('./a.js');
}
```

It seems that Madge will detect a circular dependency between these two files (`madge ... -c`). Is there a way to prevent reporting this? Ideally, I could configure Madge to _only_ report compile-time/first-pass circular dependencies, and ignore runtime require loops.

**Comment by pahen** [comment]
The entire solution is built on static analysis so handling cases like this is a bit complex. But you could always file an issue at https://github.com/dependents/node-detective-es6 and ask for support for this.
