### ISSUE TITLE
Exclude type imports in typescript while searching for circular dependencies 

### ISSUE THREAD

**Issue by vicrac** [pahen/madge#231]
Type imports in Typescript allow for circular dependencies. Example:

`moduleA.ts`
```
import * as Life from './moduleB';

export interface Person {
    age: number;
    health: number;
    // ...
}

export const live = (p: Person) => Life.goToDoctor(Life.getOld(p))

console.log(live({
    age: 65,
    health: 0.6,
}))
```
`moduleB.ts`
```
import { Person } from './moduleA'

export const getOld = (p: Person): Person => ({
    ...p,
    age: p.age + 1
})

export const goToDoctor = (p: Person): Person => ({
    ...p,
    health: Math.min(p.health * 1.2, 1)
})

```

... and this works completely fine, even though we have circular dependency (we import `Person` _type_ in `moduleB` from `moduleA` and we import whole `moduleB` to use it in `live` function in `moduleA`).

However, when I run `madge --circular --extensions ts .` in directory containing these two files, I get:
```
Processed 2 files (584ms) 

✖ Found 1 circular dependency!

1) moduleA.ts > moduleB.ts
```

Sooo precisely my question is:
### Is there a possibility of excluding type imports from checking for circular deps?

And before someone advises to move `Person` model to a separate file both modules will be dependent on... well, it's an example. I have a muuuuuch bigger legacy project where magde has found literally hundreds of circular dependencies due to type imports, and I have no perspective of quickly fixing them in an elegant way. I'd like just to have a tool to tell me which of these are real problems, since apparently typescript compiler doesn't do this on his own.

Anyway, thanks for help in advance! (And for tool, it's really nice!)

**Comment by pahen** [comment]
See https://github.com/pahen/madge/blob/master/README.md#how-to-ignore-import-in-type-annotations-in-typescript

**Comment by vicrac** [comment]
@pahen Thanks for pointing that out. I've put the following into `.madgerc` file:
```
{
	"detectiveOptions": {
		"ts": {
			"skipTypeImports": true
		}
	}
}
```
 inside a root directory (one I run `madge` command from) but it still yields at me having detected circular dependencies :D Is that correct path for it?

**Comment by vicrac** [comment]
@pahen I made sure I have correctly turn these options you mentioned on, and I now am starting to think it is some weird bug in `madge` itself. Could you tell me if you are able to reproduce it (I am using the latest version of `madge`)?
