### ISSUE TITLE
v3.6.0 breaks node 6 support

### ISSUE THREAD

**Issue by e110c0** [pahen/madge#234]
by upgrading ora to a version >=4.0.0, madge does not run in node 6 anymore.
ora 4.0.0 and higher requires node 8 as a minimum

**Comment by pahen** [comment]
I don't have any plans on supporting old versions. I support the LTS version on https://nodejs.org/en/

**Comment by e110c0** [comment]
which is fine, but then the package.json should not state that node version >=6:
` "engines": {
    "node": ">=6.x.x"
  },`

**Comment by pahen** [comment]
Yes, I'll update that

**Comment by e110c0** [comment]
PS: node 8 already works again, so dropping node 6 support only would already be enough
