### ISSUE TITLE
Support package.json configuration

### ISSUE THREAD

**Issue by zekth** [pahen/madge#235]
As `.madgerc` is not well known around IDE, it's not detected as json formatted file. As it uses json formatting, is it thinkable to add the possibility to add madge config in the `package.json` ?

I can write a PR for this.

Also `madge` currently use `rc` ( https://github.com/dominictarr/rc ) so a priority between those configurations has to be determined.

**Comment by pahen** [comment]
Sure, wouldn't hurt to have support for that. I suppose adding madge config in package.json should have precedence over config files found by `rc`. Feel free to write a PR.
