### ISSUE TITLE
[TypeScript] Add support to skip `import type`

### ISSUE THREAD

**Issue by zekth** [pahen/madge#240]
In TypeScript 3.8 the new feature of `import type` has been introduced but Madge does not handle it. As we use the syntax `import type { Foo } from 'bar'` we can skip the import on `import type` keyword.

But note that this won't solve the problems of regular export of types and imported as modules.

I can write a PR for this if needed.

**Comment by pahen** [comment]
See https://github.com/pahen/madge#how-to-ignore-import-in-type-annotations-in-typescript
