### ISSUE TITLE
Consider using confinode

### ISSUE THREAD

**Issue by sveyret** [pahen/madge#241]
Hi,
I've just release the configuration managing library [confinode](https://www.npmjs.com/package/confinode) and I thought it could be useful to this project.
Please ask me if you have questions on need help on this.
Thank you.

**Comment by pahen** [comment]
Hi,

What will I get that isn't supported already by using that?

**Comment by sveyret** [comment]
Well, I didn't studied _Madge_ enough to be sure, but here is what I can think of:

Support for many file types: _JavaScript_, _JSON_, _YAML_ out-of-the-box, and many more if the user have some modules. For example, if the project the user is analyzing is written in _TypeScript_, an appropriate module is probably already installed that _confinode_ can use to understand _TypeScript_ configuration files.

Indirections, meaning that if the user wants to set his configuration using an unexpected file name, he can use, for example, the `package.json` entry to give this file name. For a company sharing a configuration in a module, _confinode_ can also be given a module name.

Again for a company sharing a configuration, _confinode_ manages inheritance, meaning it can take the company default configuration and overwrite only the options set in the project configuration file.

**Comment by sveyret** [comment]
On the other hand, if you are already using _rc_, I must say that _confinode_ does not parse the command line.

**Comment by pahen** [comment]
Ok, thanks. But I think I'll stick with `rc` right now.
