### ISSUE TITLE
graphviz is unde GPL license, making this wonderful module hard to use

### ISSUE THREAD

**Issue by ebdrup** [pahen/madge#244]
First of all THANKY YOU so much for making this module - It's really a life saver for checking for cyclic dependencies as an automated test.

Unfortunately I may have to stop using it as it has a  dependency on graphviz that is under the very restrictive GPL license. We are not using the graphic visualization in any way.

Would it be possible to release a version without graphviz as a dependency for those of us who do not need it, or maybe make it an optional peerDependency? That would also make the install base of this module smaller for those who don't need graphviz.

I would be happy to do a PR, if you say what you would like...

**Comment by pahen** [comment]
Glad you find it helpful! It's only required to install graphviz if you use the graphic visualization feature in Madge so shouldn't be a problem for you?

**Comment by ebdrup** [comment]
Hi pahen. I'm not a lawyer, but I would say that as long as your module uses any GPL licensed source code, the GPL License stipulates that you also have to release that source code under GPL. So I would say that means that madge is currently in violation of the graphviz license, and anyone using madge who does not also release their software under a GPL license is also in violation of the graphviz license. This means for us that we will have to stop using madge, if the graphviz depenedency is not made optional or removed.

**Comment by ebdrup** [comment]
Hmm, I just checked. I think the license checker has a bug. I'm using https://github.com/davglass/license-checker#readme
And for some reason it reports graphviz as GPL... But when I look at graphviz it's actually under the MIT License... Sorry for the confusion. I should have checked before I created an issue.

**Comment by nemtsov** [comment]
FYI: A GPL-licensed file still exists inside `node-graphviz`: https://github.com/glejeune/node-graphviz/issues/40

**Comment by joechrz** [comment]
> Glad you find it helpful! It's only required to install graphviz if you use the graphic visualization feature in Madge so shouldn't be a problem for you?

It looks like madge installs graphviz as an internal dependency, so this is unfortunately outside of our control.

**Comment by pahen** [comment]
> > Glad you find it helpful! It's only required to install graphviz if you use the graphic visualization feature in Madge so shouldn't be a problem for you?
> 
> It looks like madge installs graphviz as an internal dependency, so this is unfortunately outside of our control.

Sorry, has to be fixed in https://github.com/glejeune/node-graphviz/issues/40
