### ISSUE TITLE
[Feat] generate subgraph of dependencies

### ISSUE THREAD

**Issue by sibelius** [pahen/madge#254]
How can I generate a subgraph from a give file

Use case: 

I'd like to know all "internal" files that depends on a give File

![image](https://user-images.githubusercontent.com/2005841/88109077-427d9400-cb80-11ea-8830-e2207b7adf35.png)

Package B subgraph would be, package A and babel (just change package for files in the example to make sense)

**Comment by PabloLION** [comment]
@sibelius Can you check if this is a dup of #254 ? Also I think the solution to #181 may help you as well.

**Comment by c-vetter** [comment]
@PabloLION 
> @sibelius Can you check if this is a dup of #254 ? Also I think the solution to #181 may help you as well.

You linked the current issue as a potential duplicate. I did a quick search and couldn't identify the issue you may have meant.

#181 seems orthogonal to this issue.

@sibelius
You can use the JS/TS interface to crawl the graph for your needs. Just call `.obj()` and assemble the subgraph as required.
