### ISSUE TITLE
[Question/feature Request] run synchronously 

### ISSUE THREAD

**Issue by mammadataei** [pahen/madge#255]
Hi, I need a way to generate graphs synchronously? how can I achieve this?

**Comment by Deven-x** [comment]
same question

**Comment by pahen** [comment]
I have no plans to add a synchronous version of the API. You can always execute the Madge CLI from node synchronously and parse the output.

**Comment by mammadataei** [comment]
Ok, I think it's going to work for me. Just. how should I parse the output to madge object?

**Comment by pahen** [comment]
Use the `--json` option to the CLI
