### ISSUE TITLE
Missing @types/madge

### ISSUE THREAD

**Issue by mateja176** [pahen/madge#256]
Madge already has great docs, hence writing type declarations for the API should be a smooth process. Though, the current situation is as follows:

```txt
Could not find a declaration file for module 'madge'. 'project/node_modules/madge/lib/api.js' implicitly has an 'any' type.
  Try `npm install @types/madge` if it exists or add a new declaration (.d.ts) file containing `declare module 'madge';`
```

Moreover, `yarn add -D @types/madge` yields:
```
yarn add v1.22.4
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2fmadge: Not found".
info If you think this is a bug, please open a bug report with the information provided in "project/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by jasongerbes** [comment]
I have created a PR to add types for Madge to DefinitelyTyped:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54486

**Comment by pahen** [comment]
> I have created a PR to add types for Madge to DefinitelyTyped:
> [DefinitelyTyped/DefinitelyTyped#54486](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54486)
> 
> @pahen it would be great if you could take a look over it.
> 
> Here's a [TypeScript Playground](https://www.typescriptlang.org/play?&dtPR=54486&install-plugin=playground-dt-review#code/JYWwDg9gTgLgBCAhgEwOYFMA0cDecCyKGAwhAHYBmwq2ha6AkmQM4yJkDG6cAvnBVAgg4AIiT0RAbgBQ0gPRy4AdXQAbDkO4wIcGAAtuAFQCeYdAGUOUYGHgAFVYmOpBAVzLJs+4Mzg+4iHAA7ugARszAMOjyikF6wBx6cKjAAG7ovsYQrgFwiexcujpB1lHYzHqIUNzsyHCq6FVkcCZmlta2AHSyCnAAmtl52ap13mQA1nAQFH7wwM361dxBTswAXDExcHAAtHAAgnBgjoXa9Y1Qza0WVjZzzYHHiIVx6NVwZBBjqHnscKHVRDjLa7A5HE5aHToAAeZmsIHQZHgQUiSWu7TucGYxiRiGh2FqWMq7303AAqgAlAAyvhR+impKgzBBe0OzFqoQg0KKcBhcNAiORqLgyGAFAob0FQ3AwAaUH4jRgrmqvmmLVMNw6MFk4gwAAoxMY5GBEPoRABKTqksh6lVwAC8AD44CrOhBQgArPXm80yaQaFjwANUVBrAhEdCkSjUB24f6IZjoAAiwCgYZEoqgIl4MgDrAQYboGCYrAK3HtARWkQQEYNICNJrN2GD1F9Ordnu9MhAnRWl3mqGYXekPY4qY4rkcUGHo-Hk6qAHEoIgwHoZ51kOgzB4hwByYDIXdtnvQVfsIfHzoNRDpC-djdfPUwKCudCX0CIfW7xt6XdeF9vvezCpKgw5AA) for these types.

Sorry for my lack of response. Vacation time here. Thanks for you efforts @jasongerbes 🥇
