### ISSUE TITLE
Error: Graphviz could not be found. Ensure that "gvpr" is in your $PATH.

### ISSUE THREAD

**Issue by djmisterjon** [pahen/madge#257]
i think i have issue here ! 
![image](https://user-images.githubusercontent.com/24865815/90398296-2da0fd00-e067-11ea-9e8f-732934b254ec.png)
am trying generate a image of module hierarchy from a react projet !
How i can perform this ?

i have installed https://www.npmjs.com/package/graphviz-cli  globally !

**Comment by Hari-Soni** [comment]
I am also facing the same problem. Were you able to resolve the problem?

**Comment by djmisterjon** [comment]
yes yep, when you install `Graphviz` be sure to add path in your global env, it because the install of Graphviz are buggy.
![image](https://user-images.githubusercontent.com/24865815/91755813-b8224a00-eb99-11ea-9489-10973000c043.png)

**Comment by Vaylle** [comment]
I have the same problem except I added it to path...

![image](https://user-images.githubusercontent.com/70904816/94516278-bfcf2000-0225-11eb-9a87-49abf6ff3b2d.png)

![image](https://user-images.githubusercontent.com/70904816/94516200-91e9db80-0225-11eb-81b2-793ef734239e.png)

**Comment by darzang** [comment]
I'm getting the same issue, I have the PATH variable set (in both System and User) pointing to the \bin, but I'm still getting the "Graphviz could not be found. Ensure that "gvpr" is in your $PATH." error when running "madge --circular --image graph.svg ./"

I tried to follow this answer: https://stackoverflow.com/questions/39886313/graphviz-gvpr-is-not-recognized
But I ended up with this error : " Error: write EPIPE"

So I looked for this error, and stumble upon this: https://github.com/pahen/madge/issues/78
But I already have my Path variable set, so I'm not sure what I can now ...

**Comment by djmisterjon** [comment]
> I'm getting the same issue, I have the PATH variable set (in both System and User) pointing to the \bin, but I'm still getting the "Graphviz could not be found. Ensure that "gvpr" is in your $PATH." error when running "madge --circular --image graph.svg ./"
> 
> I tried to follow this answer: https://stackoverflow.com/questions/39886313/graphviz-gvpr-is-not-recognized
> But I ended up with this error : " Error: write EPIPE"
> 
> So I looked for this error, and stumble upon this: #78
> But I already have my Path variable set, so I'm not sure what I can do now ...

i dont know what to say , it should work ! 
`Graphviz -V` should give you the Graphviz version and tell you all is fine.
If not , is because you do some mistake in your path.
Be sure your have correct autorisation and your are in **Admin** mode (not needed but sometime it can help) !

**Comment by darzang** [comment]
I tried in Admin mode and still got the error.
But I get a "'Graphiz' is not recognized as an internal or external command, operable program or batch file."  when running Graphviz -V (same for graphviz -V) so it's probably related.
Here is my user environment variables:
![envVariables](https://user-images.githubusercontent.com/25525851/102991239-1db78f00-4519-11eb-9955-896fd5afd042.png)

One thing that is different for me than for the OP though is that I'm not using graphviz-cli as the node version used in the projet is 10 and the cli requires at least node 12. I didn't find any information on the minimum node version to use the "original" Graphviz downloaded from https://www2.graphviz.org/Packages/stable/windows/10/cmake/Release/x64/
And once installed, there is no gvpr.exe in the bin folder.
I'm starting to think that in the end this might be an issue related to graphviz more than madge

**Comment by djmisterjon** [comment]
> I tried in Admin mode and still got the error.
> But I get a "'Graphiz' is not recognized as an internal or external command, operable program or batch file." when running Graphviz -V (same for graphviz -V) so it's probably related.
> Here is my user environment variables:
> ![envVariables](https://user-images.githubusercontent.com/25525851/102991239-1db78f00-4519-11eb-9955-896fd5afd042.png)
> 
> One thing that is different for me than for the OP though is that I'm not using graphviz-cli as the node version used in the projet is 10 and the cli requires at least node 12. I didn't find any information on the minimum node version to use the "original" Graphviz downloaded from https://www2.graphviz.org/Packages/stable/windows/10/cmake/Release/x64/
> And once installed, there is no gvpr.exe in the bin folder.
> I'm starting to think that in the end this might be an issue related to graphviz more than madge

you link seem wrong.
you use 
`C:\Program Files`
it should 
`C:\Program Files (x86)`

C:\Program Files is habitually for x64 softwares.
Try x86 folder

**Comment by themrhead** [comment]
GraphViz installation only brings the .exe files listed bellow as for v2.44.1.
Thus gvpr.exe seems to be a wrong reference. Any clue?


```
→ C:\Program Files (x86)\Graphviz 2.44.1\bin› gci -Filter *exe
-a---        29/06/2020     06:03    11,50KB acyclic.exe
-a---        29/06/2020     06:03    14,00KB bcomps.exe
-a---        29/06/2020     06:03    19,50KB ccomps.exe
-a---        29/06/2020     06:04    14,50KB dijkstra.exe
-a---        29/06/2020     06:04    10,00KB dot.exe
-a---        29/06/2020     06:04    14,00KB gc.exe
-a---        29/06/2020     06:04    32,50KB gml2gv.exe
-a---        29/06/2020     06:04    17,50KB graphml2gv.exe
-a---        29/06/2020     06:04    27,50KB gvcolor.exe
-a---        29/06/2020     06:04    19,00KB gvgen.exe
-a---        29/06/2020     06:04   102,00KB gvpack.exe
-a---        29/06/2020     06:04    29,50KB gxl2gv.exe
-a---        29/06/2020     06:04    28,00KB mm2gv.exe
-a---        29/06/2020     06:05    11,50KB nop.exe
-a---        29/06/2020     06:05    14,00KB sccmap.exe
-a---        29/06/2020     06:05    14,00KB tred.exe
-a---        29/06/2020     06:05    13,50KB unflatten.exe
```

**Comment by thiago-nsjob** [comment]
> GraphViz installation only brings the .exe files listed bellow as for v2.44.1.
> Thus gvpr.exe seems to be a wrong reference. Any clue?
> 
> ```
> → C:\Program Files (x86)\Graphviz 2.44.1\bin› gci -Filter *exe
> -a---        29/06/2020     06:03    11,50KB acyclic.exe
> -a---        29/06/2020     06:03    14,00KB bcomps.exe
> -a---        29/06/2020     06:03    19,50KB ccomps.exe
> -a---        29/06/2020     06:04    14,50KB dijkstra.exe
> -a---        29/06/2020     06:04    10,00KB dot.exe
> -a---        29/06/2020     06:04    14,00KB gc.exe
> -a---        29/06/2020     06:04    32,50KB gml2gv.exe
> -a---        29/06/2020     06:04    17,50KB graphml2gv.exe
> -a---        29/06/2020     06:04    27,50KB gvcolor.exe
> -a---        29/06/2020     06:04    19,00KB gvgen.exe
> -a---        29/06/2020     06:04   102,00KB gvpack.exe
> -a---        29/06/2020     06:04    29,50KB gxl2gv.exe
> -a---        29/06/2020     06:04    28,00KB mm2gv.exe
> -a---        29/06/2020     06:05    11,50KB nop.exe
> -a---        29/06/2020     06:05    14,00KB sccmap.exe
> -a---        29/06/2020     06:05    14,00KB tred.exe
> -a---        29/06/2020     06:05    13,50KB unflatten.exe
> ```

I can relate to this fact. There is no gvpr on the installation folder on 2.44.1, guess that is why the path confi is not working at all. Not sure what to do.

**Comment by gajdikuka** [comment]
> > GraphViz installation only brings the .exe files listed bellow as for v2.44.1.
> > Thus gvpr.exe seems to be a wrong reference. Any clue?
> > ```
> > → C:\Program Files (x86)\Graphviz 2.44.1\bin› gci -Filter *exe
> > -a---        29/06/2020     06:03    11,50KB acyclic.exe
> > -a---        29/06/2020     06:03    14,00KB bcomps.exe
> > -a---        29/06/2020     06:03    19,50KB ccomps.exe
> > -a---        29/06/2020     06:04    14,50KB dijkstra.exe
> > -a---        29/06/2020     06:04    10,00KB dot.exe
> > -a---        29/06/2020     06:04    14,00KB gc.exe
> > -a---        29/06/2020     06:04    32,50KB gml2gv.exe
> > -a---        29/06/2020     06:04    17,50KB graphml2gv.exe
> > -a---        29/06/2020     06:04    27,50KB gvcolor.exe
> > -a---        29/06/2020     06:04    19,00KB gvgen.exe
> > -a---        29/06/2020     06:04   102,00KB gvpack.exe
> > -a---        29/06/2020     06:04    29,50KB gxl2gv.exe
> > -a---        29/06/2020     06:04    28,00KB mm2gv.exe
> > -a---        29/06/2020     06:05    11,50KB nop.exe
> > -a---        29/06/2020     06:05    14,00KB sccmap.exe
> > -a---        29/06/2020     06:05    14,00KB tred.exe
> > -a---        29/06/2020     06:05    13,50KB unflatten.exe
> > ```
> 
> I can relate to this fact. There is no gvpr on the installation folder on 2.44.1, guess that is why the path confi is not working at all. Not sure what to do.

On windows it has a different name: 'dot.exe'

Try copying 'dot.exe' and rename it to 'gvpr.exe'

**Comment by MageeLin** [comment]
> > > GraphViz installation only brings the .exe files listed bellow as for v2.44.1.
> > > Thus gvpr.exe seems to be a wrong reference. Any clue?
> > > ```
> > > → C:\Program Files (x86)\Graphviz 2.44.1\bin› gci -Filter *exe
> > > -a---        29/06/2020     06:03    11,50KB acyclic.exe
> > > -a---        29/06/2020     06:03    14,00KB bcomps.exe
> > > -a---        29/06/2020     06:03    19,50KB ccomps.exe
> > > -a---        29/06/2020     06:04    14,50KB dijkstra.exe
> > > -a---        29/06/2020     06:04    10,00KB dot.exe
> > > -a---        29/06/2020     06:04    14,00KB gc.exe
> > > -a---        29/06/2020     06:04    32,50KB gml2gv.exe
> > > -a---        29/06/2020     06:04    17,50KB graphml2gv.exe
> > > -a---        29/06/2020     06:04    27,50KB gvcolor.exe
> > > -a---        29/06/2020     06:04    19,00KB gvgen.exe
> > > -a---        29/06/2020     06:04   102,00KB gvpack.exe
> > > -a---        29/06/2020     06:04    29,50KB gxl2gv.exe
> > > -a---        29/06/2020     06:04    28,00KB mm2gv.exe
> > > -a---        29/06/2020     06:05    11,50KB nop.exe
> > > -a---        29/06/2020     06:05    14,00KB sccmap.exe
> > > -a---        29/06/2020     06:05    14,00KB tred.exe
> > > -a---        29/06/2020     06:05    13,50KB unflatten.exe
> > > ```
> > 
> > 
> > I can relate to this fact. There is no gvpr on the installation folder on 2.44.1, guess that is why the path confi is not working at all. Not sure what to do.
> 
> On windows it has a different name: 'dot.exe'
> 
> Try copying 'dot.exe' and rename it to 'gvpr.exe'
> 
> Also run cmd in Administrator mode

Perfect！

**Comment by 840583540** [comment]
How to solve MacOS?

**Comment by PabloLION** [comment]
Closing this issue. Solutions are
Windows: https://github.com/pahen/madge/issues/257#issuecomment-768155223
Mac: https://github.com/pahen/madge/issues/257#issuecomment-1145227888

**Comment by djmisterjon** [comment]
> 

no solution are in your OS env variables!
https://github.com/pahen/madge/issues/257#issuecomment-683965489

**Comment by PabloLION** [comment]
@djmisterjon Thanks for the correction ❤️
