### ISSUE TITLE
How can i get all the dependecies outside then arrow function body?

### ISSUE THREAD

**Issue by Kelin-hao** [pahen/madge#265]
The api explains:
`madge(path).then((res) => {
	console.log(res.obj())
})`
I try to use the statement to get dependency  
`var depend = madge(path).then((res) => {
return res.obj()
})`
But i get the wrong result in the console:
`Promise { <pending> }`
I donot know how to revise the code as i am not familiar with js language.

**Comment by Wang-JLU** [comment]
Finally, I use then() function chain to deliver the value.If there exists any good solutions?

**Comment by syea911** [comment]
> Finally, I use then() function chain to deliver the value.If there exists any good solutions?

you can try to use await
