### ISSUE TITLE
Methods / Property / Variables graph.

### ISSUE THREAD

**Issue by infacto** [pahen/madge#270]
Is it possible to make the same stuff for methods / properties / variables? Instead of path / files. Example: 
You have a file with a class. And you want to display the network of references.

```ts
class MyService {
  public one(txt = 'one'): void {
    console.log(txt);
  }

  public two(): void {
    this.one('two');
  }
}

// Another file
class AnotherService {
  constructor(myService: MyService) {
    myService.two();
  }
}
```

Results in something like that: 

```
AnotherService.constructor > MyService.two > MyService.one
```

**Comment by pahen** [comment]
Sorry. You have to make a dedicated tool for that.
