### ISSUE TITLE
How to get real dependency file?

### ISSUE THREAD

**Issue by syea911** [pahen/madge#279]
The utils/index.js like this:
export * from './browser';
export * from './DevTools';
export * from './request';
export * from './getServerData';
export * from './others';

The utils/other.js like this:
export const functionA =()=>{//some code here};
export const functionB = ()=>{//some code here}；

A components file expamle ImageUploader.js  like this;
import {functionA,functionB} from "@/utils"；

the output is:
imageUploader.js:[
   utils/index.js
]
But I expect the output is:
imageUploader.js:[
   utils/others.js
]

**Comment by PabloLION** [comment]
It seems you imported a function `f` in file `A` from file `B`, and also in file `B` from file `C`. So madge should show the import `A->B->C`  ( `C` is dependency of `B`, `B` is dependency of `A`). This seems correct for me.

My `f` is the "functionA , functionB" in your example.
