### ISSUE TITLE
It doesn't return any dependencies when there is a labeled tuple type in the file

### ISSUE THREAD

**Issue by andormade** [pahen/madge#297]
It is very easy to reproduce, just add this line to one of your TypeScript source files:

```
type LabeledTuple = [something: number];
```

It doesn't matter whether I use my own tsconfig file or not. It's probably because madge is using TypeScript 3.

**Comment by PabloLION** [comment]
This should be gone in v6. Can someone double check please?

**Comment by kamiazya** [comment]
It's closed by v6.

Thanks.
