### ISSUE TITLE
Old typescript dependency

### ISSUE THREAD

**Issue by kohtala** [pahen/madge#308]
vscode fails to start TypeScript language service when an old typescript is present in the workspace. Having madge brings an old typescript into workspace.

> The TypeScript language service died 5 times right after it got started. The service will not be restarted.

https://github.com/microsoft/vscode/issues/138794

I don't think the vscode language service is quite fixed, but it would do no harm to have madge upgrade the dependency.

**Comment by kohtala** [comment]
On closer inspection it seems the vscode problem is not related to the old dependency.

I'll leave this here open for a while anyway since it still is an old dependency.

**Comment by PabloLION** [comment]
already solved by
- https://github.com/pahen/madge/pull/350
