### ISSUE TITLE
`tsconfig.json` with `extends` not handled correctly

### ISSUE THREAD

**Issue by eelco** [pahen/madge#323]
When passing a `tsconfig.json` to `--ts-config` madge does not handle the `extends` field correctly.

It is calling all the “right” options to parse the file with TypeScript, but then ends up taking the `raw` field as the options: https://github.com/pahen/madge/blob/715f1a08afa6cae2176cdf06ab7ba851b6f0d439/bin/cli.js#L118

This is not correct. Compare to how `filing-cabinet` fixed the same issue: https://github.com/dependents/node-filing-cabinet/pull/86 That code ends up using `options` for the processed `compilerOptions`, which is the result of merging in the options as configured via the file referred to with `extends`.

Found during debugging for this related issue: https://github.com/pahen/madge/issues/322

**Comment by fdc-viktor-luft** [comment]
@kamiazya will this be possibly fixed in V6?

**Comment by kamiazya** [comment]
@fdc-viktor-luft 
I will work on it, but it may take some time to debug.

I think the response is that it is not required in the v6 release, but will be included if it is ready in time.
