### ISSUE TITLE
Providing a directory does not work with TypeScript

### ISSUE THREAD

**Issue by m-gallesio** [pahen/madge#326]
Providing a directory as a parameter does not seem to make the program recognize TypeScript files.
It does work with plain JavaScript.
TypeScript files are recognized when passed explicitly.

This test was done in PowerShell on Windows 10 with madge 5.0.1

```
PS [MY_APPLICATION_PATH]> madge -i deps.svg .\src\main.ts
Processed 1 file (842ms) (3 warnings)

✔ Image created at [MY_APPLICATION_PATH]\deps.svg

PS [MY_APPLICATION_PATH]> madge -i deps.svg .\src
Processed 0 files (1s)

✔ Image created at [MY_APPLICATION_PATH]\deps.svg

PS [MY_APPLICATION_PATH]> mv .\src\main.ts .\src\main.js
PS [MY_APPLICATION_PATH]> madge -i deps.svg .\src
Processed 1 file (1s)

✔ Image created at [MY_APPLICATION_PATH]\deps.svg
```

**Comment by PabloLION** [comment]
have you tried with `tsconfig` option / flag?

**Comment by m-gallesio** [comment]
No difference, even after updating to 6.0.0
```
PS [MY_APPLICATION_PATH]> madge -i deps.svg --ts-config .\tsconfig.json .\src
Processed 0 files (1.4s)

✔ Image created at [MY_APPLICATION_PATH]\deps.svg
```

**Comment by khlevon** [comment]
@m-gallesio 
I think I faced this kind of problem, and I solved it by passing a directory path like this 
`madge --circular --image graph.svg --warning --extensions=ts src/**/**/**/**/**` 

Note: you should pass exactly the depth of your folder structure; otherwise, you will get an error like this 
`zsh: argument list too long: madge`

**Comment by m-gallesio** [comment]
> `madge --circular --image graph.svg --warning --extensions=ts src/**/**/**/**/**`
I have tried and just `--extensions=ts` is enough; thank you for your input.
