### ISSUE TITLE
Legacy octal literals are not allowed in strict mode

### ISSUE THREAD

**Issue by DanTrofimov** [pahen/madge#327]
Sup 👋

That issue relates to the - https://github.com/pahen/madge/issues/214

## Intro:
Versions of Madge and Jest, which I'm using:
```json
"madge": "5.0.1",
"jest": "26.6.3"
```
## Description:

Getting that logs during testing Madge with Jest, when I'm trying to import `madge` function at `**.test.js` files:
```js
SyntaxError: /node_modules/graphviz/node_modules/temp/lib/temp.js:
Legacy octal literals are not allowed in strict mode (101:20)

   99 | var mkdir = function(affixes, callback) {
  100 |   var dirPath = generateName(affixes, 'd-');
> 101 |   fs.mkdir(dirPath, 0700, function(err) {
      |                     ^
  102 |     if (!err) {
  103 |       deleteDirOnExit(dirPath);
  104 |     }
```

In the `jest.config` I have configured `transformIgnorePatterns` to not parse the `node_modules/graphviz` (as discussed at https://github.com/pahen/madge/issues/214), but I've got the same issue.

So, bumping `temp` to the `0.9.0` version in the `package.json` for Yarn helped me:
```json
"resolutions": {
  "madge/graphviz/temp": "~0.9.0"
},
```

## Proposal:

Now it works fine. @pahen, what do you think about adding something similar to the `madge`, untill `graphviz` bump the `temp` version? 

Thanks ✨

**Comment by DanTrofimov** [comment]
<img src="https://user-images.githubusercontent.com/44056222/208254719-c8d361a6-6876-48d6-a69a-f48b9bb9c9ab.png" width="500" />

**Comment by DanTrofimov** [comment]
https://www.youtube.com/shorts/fYYr8kktCvI

**Comment by kamiazya** [comment]
I have confirmed that the dependency on temp is no longer present in the current master.

The next release will resolve this issue!

```bash
node ➜ /workspaces/madge (master) $ git show-ref master
13d38a7cf83c443735a75ae0e1edd6392c26150c refs/heads/master
13d38a7cf83c443735a75ae0e1edd6392c26150c refs/remotes/origin/master
node ➜ /workspaces/madge (master) $ npm i

up to date, audited 603 packages in 722ms

171 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
node ➜ /workspaces/madge (master) $ ls node_modules/ | grep temp | wc -l
0
```

close.
