### ISSUE TITLE
Node 18 not supported because of outdated "detective-postcss" dependency

### ISSUE THREAD

**Issue by fdc-viktor-luft** [pahen/madge#329]
Please update the "detective-postcss" package as this one has currently no support for Node 18.

**Comment by fdc-viktor-luft** [comment]
Would be fixed by: https://github.com/pahen/madge/pull/319

**Comment by viceice** [comment]
I've posted another issue upstream to loosen the node restrictions for v5.x

- https://github.com/dependents/node-detective-postcss/issues/201

**Comment by kamiazya** [comment]
https://github.com/pahen/madge/pull/319 was marged.

close.
