### ISSUE TITLE
Add cli option to print warnings

### ISSUE THREAD

**Issue by 0x80** [pahen/madge#338]
When I run the CLI it tells me there are 167 warnings in my repo, but I see no way of inspecting those warnings, so a CLI flag would be helpful I think.

**Comment by michal-kurz** [comment]
If I understand correctly: you can try running with `--warning` flag, this might give you a basic idea. Using `--debug` flag will give you a complex debug output, which is very verbose and noisy, but should tell you all there is to log :)

**Comment by 0x80** [comment]
Thanks that works! I don't know how I missed that option 🤦‍♂️
