### ISSUE TITLE
Is it possible to exclude dynamically imported modules?

### ISSUE THREAD

**Issue by 1226085293** [pahen/madge#344]
I need to exclude dynamically imported modules from inspection, e.g. `import("../xxx")`

**Comment by mvlabat** [comment]
+1, a flag to exclude dynamic imports would be useful. Dynamic imports don't immediately affect time to require a parent module and/or bundle sizes, excluding them would make it easier in cases when we're trying to optimise module sizes.

**Comment by PabloLION** [comment]
@1226085293 is this a dup of #328?

**Comment by oddguan** [comment]
see #360
