### ISSUE TITLE
Release v6.0.0

### ISSUE THREAD

**Issue by kamiazya** [pahen/madge#347]
I have created a temporary Issue because GitHub Disscussion cannot be activated under my authority.

Use it to discuss the pros and cons of releasing [v6.0.0](https://github.com/pahen/madge/milestone/3).

**Comment by kamiazya** [comment]
@pahen @fdc-viktor-luft @PabloLION 

I have fixed one of the glaring issues I discovered, but I will try to make decisions as a community to see if there is anything else that can be fixed.

@fdc-viktor-luft asked if #323 could be fixed, but think it's optional to fix in this release.

If you think it's okay to release it with this content, please respond with :+1:.
Since we don't have a decision-making mechanism in place as a community yet, I'd like to release it with :+1: from at least 2 Collabolators or Owners.

**Comment by PabloLION** [comment]
#332 needs us to update the CI. Since in v6 we are adding supporting for Node 18+ (notice that [Node.js 19 is now available!](https://nodejs.org/en/blog/announcements/v19-release-announce/), the CI should be updated as well.

Currently we are running it with node 10,12,13 [details here](https://app.travis-ci.com/github/pahen/madge/builds/257583312). I'm nor sure if we are authorized to remove old jobs on Travis CI, as we are stopping the support for node version <14. If not, we can maybe do it with [GitHub Actions](https://github.com/pahen/madge/actions/new) and just ignore the Travis CI result.

I myself know little about DevOps but I'd be glad to learn it if needed.

**Comment by kamiazya** [comment]
#332 will merge with master and try to see if the Travis CI failure goes away.

The devDependencies update may not affect users, but I thought the `detective-*` update was important for users.

**Comment by PabloLION** [comment]
Also maybe we should consider supporting node 14 as well, if there's no conflict. It's still [under official active maintenance](https://endoflife.date/nodejs) and users might not want to update it?

**Comment by kamiazya** [comment]
The versions of Node.js that we will be removing from support are 10 and 12, so we assume that users do not need to update yet:+1:

https://github.com/pahen/madge/blob/master/.travis.yml#L2-L5

https://github.com/pahen/madge/blob/master/package.json#L23-L25

**Comment by kamiazya** [comment]
#332 is importing Pure ESM-ized ora v6, which is time consuming because it requires ESM for the entire package.

If we make the decision to prioritize support for Node 18 and fix #332 later, the release can be done as is.

**Comment by kamiazya** [comment]
I created a PR for #348 as an alternative, since it is difficult to fix #332 immediately.

Please review it.

**Comment by PabloLION** [comment]
@kamiazya I'm also facing the ESM/CJS problem and I just found that in [typescript 5.0 beta](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#moduleresolution-bundler) there's a new `moduleResolution` value: `bundler` which seems to be able to handle the inconsistency among all dependencies.
I tested ts5 but it's not resolving my problem (see TL;DR) so maybe we wait for either
1. node / ts upgrade. I believe node foundation is trying to solve the same problem.
2. CJS support for ora.

### TL;DR
The [webgazer](https://www.npmjs.com/package/webgazer) package is using ESM `.mjs` and importing with relative path without extension and all vite / next 13 / vue / react template cannot resolve the import, even with `"moduleResolution" : "bundler"` in `tsconfig`.

**Comment by kamiazya** [comment]
@PabloLION Thank you for your research!

However, this is a Node.js specification that prevents importing ESModule formatted packages from CommonJS formatted modules, so it cannot be solved by TypeScript settings.

If you want to use ESModule-formatted packages such as ora v6, you need to convert the entire madge package to ESModule, and specifically do the following, among other things.

- Specify "module" in the type field of package.json.
- Rewrite the source code to ESModule format.
  - e.g. using import to import the package with require, etc.

Since madge packages are written in CommonJS format and this does not affect users, we will not support it in the v6.0.0 release.

In fact, it works on the supported 14 to 18 node versions on CI, and we have confirmed that there are no vulnerabilities in npm audit or other dependent packages, so there is no harm to users.

**Comment by PabloLION** [comment]
Thanks for the explanation!
Maybe we should change the package.json to equivalente `"ora": ">=5.4.1<6.0.0",` to emphasise it's not compatible with ora v6.

**Comment by kamiazya** [comment]
@PabloLION 
Personally, I thought the current designation of `^5.4.1` was sufficient, since the ora package is also versioned based on semantic versioning.

Perhaps the advantage of package management in package.json is that it eliminates redundant specifications such as those in ranges, and I don't really want to change what is currently working well.

https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004

**Comment by kamiazya** [comment]
@pahen @PabloLION @fdc-viktor-luft 

I worked on it all day yesterday and it seems to be ready for v6 release as there seem to be no bugs that would make it suitable for a major version upgrade.

There are other bugs, but we think we can release them later in a patch release.

I voted :+1: on the issue description and would be willing to release it if another person votes for it.

If you have any suggestions for this bug to be fixed in a major update, please let me know.

I look forward to your feedback!

**Comment by fdc-viktor-luft** [comment]
I'd say we can release without fixing the bug if you have the feeling it is a higher risk.

Just for my understanding. It is a major release since we will afterwards require higher Node version >= 14. We should documented this in the Changelog.

@PabloLION I've many experiences with GitHub Actions. If at some point you want to consider it instead of Travis, I can create the workflows. I've already started migrating all of my projects from Travis to GitHub Actions.

**Comment by kamiazya** [comment]
@fdc-viktor-luft I think it is more of a kind of early release rather than a risk of revision.
I can't figure out how busy the collaborators are, but I figured it would take time to verify all the PRs.

CHANGELOG is an auto-generated system, so we checked it by sending it to standard output.

It is updated and announced to users at the time of release, just in case.

```bash
$ npx auto-changelog --stdout --unreleased 
### Changelog

All notable changes to this project will be documented in this file. Dates are displayed in UTC.

Generated by [`auto-changelog`](https://github.com/CookPete/auto-changelog).

#### [Unreleased](https://github.com/pahen/madge/compare/v5.0.2...HEAD)

- Update packages detective-* to latest [`#348`](https://github.com/pahen/madge/pull/348)
- chore: bump 'detective-typescript' package to allow newer TS versions [`#321`](https://github.com/pahen/madge/pull/321)
- Replace to ts-graphviz package [`#341`](https://github.com/pahen/madge/pull/341)
- chore: bump detective-postcss to v6 [`#319`](https://github.com/pahen/madge/pull/319)
- Drop support Node.js EOL versions(&lt;14) [`#342`](https://github.com/pahen/madge/pull/342)
- Changed to depend on the ts-graphviz package [`9b9ae87`](https://github.com/pahen/madge/commit/9b9ae878622be4a58951c5fcb9d46cc0c44e4593)
- update packages detective-* to latest [`60b6557`](https://github.com/pahen/madge/commit/60b6557efc5a1da04452dfc0f0b1a0281f9c8776)
- Set to Node.js 16 by default on nvm [`383452b`](https://github.com/pahen/madge/commit/383452b55294e3db1d8a9ef071b8b040ca295e14)

...
```

**Comment by PabloLION** [comment]
@kamiazya 
> Personally, I thought the current designation of `^5.4.1` was sufficient, since the ora package is also versioned based on semantic versioning.

I'm not sure what the conventions are. I personally tend to a special semantic versioning tag with same effect to distinguish the package from the version number comes "by default" to emphasize ora v6 is not compatible, reminding myself not to try to update ora to v6 next time.

> I worked on it all day yesterday and it seems to be ready for v6 release as there seem to be no bugs that would make it suitable for a major version upgrade.

Agreed. The milestone is finished, also in this way we can add the most important node 18 support.
Also, we can fix bugs in v6.1.

@fdc-viktor-luft 
Thanks for offering the help. Actually @kamiazya updated the `.travis.yml` already in #342. And it's working! So it's not as important as I thought. 
And about the migration: I read (like this[GITHUB ACTIONS VS TRAVIS CI](https://devopsauthority.tech/2021/02/09/which-is-better-github-actions-circle-ci/)), I see there's not much benefit of the migration. Please correct me if I'm wrong 🥰

**Comment by kamiazya** [comment]
@PabloLION 
> > Personally, I thought the current designation of ^5.4.1 was sufficient, since the ora package is also versioned based on semantic versioning.
>
> I'm not sure what the conventions are. I personally tend to a special semantic versioning tag with same effect to distinguish the package from the version number comes "by default" to emphasize ora v6 is not compatible, reminding myself not to try to update ora to v6 next time.

I also think it's a matter of taste, so I'll leave it up to you on this one. If you want to modify it, please create a PR.

As long as the dependencies are the same before and after the change, and the operation can be verified, there should be no problem.

**Comment by fdc-viktor-luft** [comment]
@PabloLION Pros for GitHub Actions:

- GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners. Whereas Travis *supports* getting additional free minutes for open source projects, but you need to request it.
- More flexibility (but we very likely don't need it here)

@kamiazya Doesn't it make sense to drop TS < 4 support, too? TS 5 is around the corner. Afaik there are actually no breaking changes, but that would allow us to update the TS version here, too.

**Comment by kamiazya** [comment]
@fdc-viktor-luft 
Since TypeScript does not follow the policy of semantic versioning, it is not practical to stop supporting it.

Also, the only processing related to TypeScript in madge is the resolution of tsconfig, and most of the process of building the dependency tree is an algorithm owned by detect-typescript, so the supported version of TypeScript is outside our purview.

**Comment by fdc-viktor-luft** [comment]
👍

**Comment by kamiazya** [comment]
Thank you @fdc-viktor-luft!

@kamiazya (myself) and @fdc-viktor-luft have :+1: (`:+1:`) reactions and we have exceeded the predetermined criteria of at least 2 contributors, so I will release it.

**Comment by kamiazya** [comment]
@fdc-viktor-luft @PabloLION @pahen 
The direct push to the master branch failed, but the release has been made due to TravisCI's package.json change detection.
Can someone please help me get it maege.

https://github.com/pahen/madge/pull/352

I will retype the git tags after it is imported.

**Comment by kamiazya** [comment]
@fdc-viktor-luft Thanks for approve PR!

I repushed tag.

To ALL

The release was a complete success :partying_face: 

Thank you for your cooperation!

**Comment by fdc-viktor-luft** [comment]
Thank for your effort 🎉

**Comment by pahen** [comment]
Great job guys! 🎉 🙏
