### ISSUE TITLE
Exclude imports not used at module load time

### ISSUE THREAD

**Issue by 1226085293** [pahen/madge#368]
example

a.ts
```typescript
import b from "./b";

class a {
    test(): b {
        return new b();
    }
}

export default a;
```
b.ts
```typescript
import a from "./a";

class b {
    test(): a {
        return new a();
    }
}

export default b;
```

There is no circular reference error at runtime, can exclude such imports?

.madgerc
```
{
	"detectiveOptions": {
		"ts": {
			"mixedImports": true,
			"skipTypeImports": true,
			"skipAsyncImports": true
		},
		"es6": {
			"skipTypeImports": true
		}
	}
}
```

tsconfig.json
```json
{
	"compilerOptions": {
		"target": "es6",
		"lib": ["es2015", "es2017", "ES2020", "ES2022", "dom"],
		"module": "commonjs",
		"sourceMap": true,
		"noEmit": true,
		"strict": true,
		"noImplicitAny": false,
		"downlevelIteration": true,
		"esModuleInterop": true,
		"experimentalDecorators": true,
		"allowSyntheticDefaultImports": true,
		"isolatedModules": true
	}
}
```

**Comment by phexx-hub** [comment]
How to use the madge to see dependencies in files to modules imported not via relative path?

How to configure the madge cli command?

**Comment by fdc-viktor-luft** [comment]
Madge is based on the implementation of [dependency-tree](https://github.com/dependents/node-dependency-tree), which uses "detective" packages to analyze the code. For simplicity most of them are just checking the imports. Not the actual code, see e.g. here: https://github.com/dependents/detective-typescript/blob/main/test/test.js

This means that this is not possible to detect.
