### ISSUE TITLE
Release v6.1.0

### ISSUE THREAD

**Issue by legobeat** [pahen/madge#373]
Some great improvements have been merged to master since the release of `v6.0.0` that I think will make users delighted.

https://github.com/pahen/madge/milestone/4

**Comment by kamiazya** [comment]
@legobeat 
#376 merged.

If there is anything else that should be addressed, please comment.

I will have time to work on the release this weekend.

**Comment by kamiazya** [comment]
The release is complete, but there are issues with the integrity of the master branch.

https://github.com/pahen/madge/pull/378

This issue will be closed after the above is completed.

**Comment by binjospookie** [comment]
Madge 6.1.0

```zsh
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'walkdir'
Require stack:
- /Users/binjo/Documents/work/grlt/toolchain/design-review/node_modules/madge/lib/tree.js
- /Users/binjo/Documents/work/grlt/toolchain/design-review/node_modules/madge/lib/api.js
```
