### ISSUE TITLE
Madge doesn't show Require.JS Plugins

### ISSUE THREAD

**Issue by mooyoul** [pahen/madge#39]
HI, I just found that madge doesn't show Require.JS Plugins like [require-text](https://github.com/requirejs/text), [require-async](https://github.com/millermedeiros/requirejs-plugins/blob/master/src/async.js).
Is it a bug? or not supported feature?

If it is not supported feature, can you add this to future plan?

**Comment by teehemkay** [comment]
Couldn't madge at least *list* (i.e. no need to introspect) those dependencies?
It seems to be using amdetective which does list those dependencies.
TIA
