### ISSUE TITLE
npm registry still on version 0.3.5?

### ISSUE THREAD

**Issue by Qantas94Heavy** [pahen/madge#48]
Hi, according to https://www.npmjs.com/package/madge, the current version on the npm registry is still 0.3.5. Is there any reason why version 0.4 hasn't been placed in the npm registry?

**Comment by pahen** [comment]
Thanks for the reminder! Published to NPM now.

> On 3 jan 2015, at 08:46, Karl Cheng <notifications@github.com> wrote:
> 
> Hi, according to https://www.npmjs.com/package/madge <https://www.npmjs.com/package/madge>, the current version on the npm registry is still 0.3.5. Is there any reason why version 0.4 hasn't been placed in the npm registry?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/pahen/madge/issues/48>.
> 

--
Patrik Henningsson
