### ISSUE TITLE
Bigger project does not fit in image

### ISSUE THREAD

**Issue by michaelwittig** [pahen/madge#5]
Hi. Tahnks very much for your tool! I found me cycle :)

I tried to generate a dependency map with madge --image graph.png --format amd . 
The output is an image where I cant see the project because it is "scalled down".

when i only draw the map with a part of my project like madge --image graph.png --format amd common/
everything works fine. any idea?

**Comment by alphapilgrim** [comment]
As the documentation for these options are limited as to what they do, this thread might prove to be useful to future users. @pahen you might want to have it with some disclaimer though about the image included, and it's suitability when researching from work environment.
