### ISSUE TITLE
ES6 Module Support

### ISSUE THREAD

**Issue by jimthedev** [pahen/madge#50]
Hello, 

Fantastic tool you've got here. Just wondering if you would considered supporting ES6 modules? I know the final spec wasn't out for a while but it seems like it has stabilized and might be worth considering. There is actually a project called node-detective-e6 as well: https://www.npmjs.com/package/detective-es6

Thanks much!

**Comment by pahen** [comment]
Hi,

Thanks! If I get time over I'll will absolutely take a look at this. But PRs are always welcomed in the meantime! :)

**Comment by pahen** [comment]
Support added in v0.5.0 now :)
