### ISSUE TITLE
shrinkwrap contains `resolved` and `from` fields

### ISSUE THREAD

**Issue by ricksbrown** [pahen/madge#51]
npm shrinkwrap is broken.
there is a discussion on it here: https://github.com/npm/npm/issues/3581

Until it is fixed package authors (i.e. you) have to resort to cleaning the npm-shrinkwrap.json file.
For example, angular: https://github.com/angular/angular.js/blob/master/scripts/clean-shrinkwrap.js

I'd be most grateful if you could clean your npm-shrinkwrap.json file. I would like to use madge as part of my repeatable builds but MUST use a private NPM respository.

**Comment by pahen** [comment]
I'm now using "npm-shrinkwrap" instead of "npm shrinkwrap" to get a more consistent result. See https://github.com/pahen/madge/commit/082abcb83a34aec2db0edeb728b85cf2e0be2e0b

Is this working for you?

**Comment by RickSBrown** [comment]
Thanks - that doesn't actually solve it.

For now I'm going to fix this on my end - I will write a cleanup script which I run before I add packages like Madge to our private repository.
