### ISSUE TITLE
Nested AMD/RequireJS modules not found because baseUrl not honoured

### ISSUE THREAD

**Issue by craigsnyders** [pahen/madge#56]
madge doesn't find deep nested modules because it either doesn't honour the `baseUrl` from `require.config`, or because the `baseUrl` doesn't necessarily reflect the local directory structure.

When using AMD (RequireJS) modules, the module paths may not reflect file system paths.  It would help if madge honoured the baseUrl in `require.config` object, however that won't solve all (or my) cases.  
Consider this:
**directory structure:**
```resources/
/resources
 └─── /js
      ├─── main.js              // entry point for RequireJS
      └─── /js_modules
            └─── /map
                  ├─── map.js
                  └─── tiles.js
```
**main.js**
```javascript
require.config({
    baseUrl: '/application_context/resources/js/js_modules/
});
define(['map/map'], function(map) {
    console.log('application loaded');
});
```
**map.js**
```javascript
define(['map/tiles'], function(tiles) {
    return {
        mapTiles: tiles
    }
});
```

Honouring the baseUrl won't be enough in this case, because it's purpose is for the *deployed* context, not necessarily the directory structure where main.js is found.

I would suggest adding a configurable property, such as `--require-base-url` which madge can use to evaluate AMD module paths

**Comment by ThomasCrvsr** [comment]
Hi,

I'm currently working on implementing this option but I realized that each time the path specified in this option is the same as the source :
`madge --format amd --require-base-url app/js -R app/js/config.js app/js`

Should we still consider implementing this option or using the source path for this purpose ?

**Comment by mrjoelkemp** [comment]
@ThomasCrvsr hi! I've already extracted the logic from requirejs to handle aliased paths about a baseUrl: https://github.com/mrjoelkemp/node-module-lookup-amd. I'd love to see it integrated into madge to iron out the kinks. Happy to work through it on gitter if you'd like.
