### ISSUE TITLE
Unable to retrieve requirejs child recursive dependencies

### ISSUE THREAD

**Issue by Baccanno** [pahen/madge#57]
The analyse always stops at the first layer and consider my dependencies to have no deps, which is of course not the case.

using `madge -f amd -R myconf.js -N -i out.png src`

**Comment by craigsnyders** [comment]
@Baccanno - I think that's the same root issue as the one I opened last week (https://github.com/pahen/madge/issues/56).  Do you have the same project setup where the baseUrl doesn't reflect the same location as the local file system?

**Comment by TooBug** [comment]
any update on this?

**Comment by Baccanno** [comment]
Sorry I did not continue using Madge, I resolved my issue by isolating the file that was causing trouble and load it first in its own require() callback.

**Comment by colorpump** [comment]
Same problem here: The child dependencies in my amd project are not shown.
I broke it down to a simple example.
*directories*:
```
www/
  app/
    main.js
    math.js
    messages.js
  lib/
    print.js
  config.js
```
I made sure that baseUrl reflects the same location as I call the madge cmd.
*config.js*:
```
requirejs.config({
    baseUrl: '../',  // path outside of the www folder
    paths: {
      // I left paths emtpy as madge doesn't seem to recognize them
    }
});
```
*main.js*:
```
define(['www/app/messages', 'www/lib/print'],
```
*print.js*:
```
define(['www/app/math']
```
*command*:
```
madge  ./www/app/main.js --format amd --find-nested-dependencies --dot > graph.gv
```
*output*:
```
digraph G {
  "main";
  "www/app/messages";
  "www/lib/print";
  "main" -> "www/app/messages";
  "main" -> "www/lib/print";
}
```
But I miss `"www/lib/print"->"www/app/math'"`

**Comment by colorpump** [comment]
I saw in #67 that what I'm loking for, is not implemented. I want to see the whole dependency tree. That's just possible if calling `madge ./whole_directory` but that shows me also files, which are never been called. To optimize each time my project just to run madge on it, would be annoying. A flag to get recursive dependencies, would be really nice. Until than I use a code snippet which gives me the wished result in the Browser console (also annoying): [rtree.js](https://gist.github.com/dustinboston/3288778)

**Comment by pahen** [comment]
I'm refactoring Madge now and planning to release 1.0.0 soon and will try to have this fixed then.
