### ISSUE TITLE
no transitive dependencies

### ISSUE THREAD

**Issue by tcurdt** [pahen/madge#59]
When I have a simple file with the dependency e.g. to `react`

    require("react");

the `madge` only finds

    { index: [ '../node_modules/react/react' ] }

and does not recurse any further.

I must be missing something. I want to get all transitive dependencies, too.

**Comment by iambumblehead** [comment]
I'm seeing this issue as well.

**Comment by mik01aj** [comment]
+1

**Comment by pahen** [comment]
Madge will only show dependencies for the files it finds in the folder that you gave it to scan and will not recurse into modules outside of it.

**Comment by tcurdt** [comment]
@pahen well, npm downloaded all dependencies (and their transitive dependencies) into the `node_modules` folder. So I am not sure I can follow the reason for closing this issue.

**Comment by pahen** [comment]
Madge was designed for another purpose than NPM. The intention has never been to show you an entire dependency tree. It was made to find circular dependencies in your code so including external dependencies seems odd.

**Comment by tcurdt** [comment]
"Madge will only show dependencies for the files it finds in the folder that you gave it to scan" how about scanning `node_modules` then? But nevermind - maybe just not the right tool for the job.
