### ISSUE TITLE
Issue running madge globally, excluding node_modules dir

### ISSUE THREAD

**Issue by ORESoftware** [pahen/madge#69]
I get this error when attempting this command
```
$ sudo madge --exclude ./node_modules --image graph.png .
```

https://www.dropbox.com/s/n4xd3k9xywgdtyp/Screenshot%202015-11-11%2012.36.10.png?dl=0

the error is "Error: spawn dot ENOENT"

even with sudo I get the ENOENT, it is an "unhandled error event", please advise thanks

**Comment by ORESoftware** [comment]
The call to --image graph.png seems to cause the problem, it does not seem to be the --exclude node_modules call...

**Comment by ORESoftware** [comment]
sorry, my fault, I didn't have graphviz installed, my bad

**Comment by ORESoftware** [comment]
my only advice, perhaps an error message saying that graphviz isn't installed, but otherwise just close this thanks

**Comment by pahen** [comment]
Which OS are you using?

**Comment by ORESoftware** [comment]
Mac OSX 10.9x - I think it's not a big deal - just didn't know that graphviz wasn't instead. 

I used

```$ brew install graphviz```

and it was all good after that
