### ISSUE TITLE
excluding more than one directory

### ISSUE THREAD

**Issue by ORESoftware** [pahen/madge#73]
Hi there

this one works well
```
$ madge --exclude node_modules --image source_map.png .
```
however, if I try to exclude more than 1 directory, it seems to really slow down and choke
```
 $ madge --exclude node_modules doc test artifiacts --image source_map.png .
```
am I doing something wrong?

**Comment by ORESoftware** [comment]
I also tried this, to no avail :(

```
$ madge --exclude test --exclude node_modules --image source_map.png .
```

**Comment by pahen** [comment]
The argument to exclude should be a regexp like this:

$ madge --exclude '^foo$|^bar$|^tests' /path/src

**Comment by ORESoftware** [comment]
oh shizzle

**Comment by ORESoftware** [comment]
thanks

**Comment by ORESoftware** [comment]
humma, it's slow or not working at all, it probably should be faster, is there another reason why it wouldn't work?

```
madge --exclude '^node_modules$|^test$|^artifacts$|^doc$|^json_response_templates$|^ivr_bucket_data$|^enriched_data$|^sample_data$|^sample_payloads' --image source_map.png .

```

burning CPU here

**Comment by ORESoftware** [comment]
I tried a trailing $ and without trailing $ at the end (sample_payloads) that didn't help :(

**Comment by the-homeless-god** [comment]
To help someone:

```
madge . -i dependencies.png --exclude '^packages/frontend/dist$|^packages/backend/dist'
```
