### ISSUE TITLE
does included graph.js file incorrectly reference opts.colors instead of opts.imageColors?

### ISSUE THREAD

**Issue by tjbeatrice** [pahen/madge#77]
I was having trouble to get my generated image to render with any of my custom colors passed using API:

Looking thru the code, I found in lib/graph.js some code where reference was made to an opts.colors variable, however the API uses the imageColors property instead.

For example:
```javascript
if (opts.colors) {
		G.bgcolor = opts.imageColors.bgcolor || '#000000';
		E.color = opts.imageColors.edge || '#757575';
		N.color =  opts.imageColors.dependencies || '#c6c5fe';
		N.fontcolor = opts.imageColors.fontColor || opts.imageColors.dependencies || '#c6c5fe';
	}
```

should be:

```javascript
	if (opts.imageColors) {
		G.bgcolor = opts.imageColors.bgcolor || '#000000';
		E.color = opts.imageColors.edge || '#757575';
		N.color =  opts.imageColors.dependencies || '#c6c5fe';
		N.fontcolor = opts.imageColors.fontColor || opts.imageColors.dependencies || '#c6c5fe';
	}
```

When I did a search and replace on this file alone, my images rendered based on my customized colors as expected ;)

If i was good enough with Git, i would create a pull, patch, or whatever to try and contribute... but if you do search/replace on this one file.. that is the only change.

**Comment by pahen** [comment]
It's actually correct as it is now but I'll change it so we can support both cases :-)
