### ISSUE TITLE
Update detective-es6 to v1.1.3 to support JSX

### ISSUE THREAD

**Issue by KarolAltamirano** [pahen/madge#81]
Please update detective-es6 to version 1.1.3 to make madge work well with JSX. I tried to use madge to generate graph for a react project but it was not working for files containing JSX. But when I updated detective-es6 it started to work well.

**Comment by mrjoelkemp** [comment]
@KarolAltamirano This will fix it once merged: https://github.com/pahen/madge/pull/83

**Comment by KarolAltamirano** [comment]
great :+1:
