### ISSUE TITLE
CJS Modules show with abolute path in Windows

### ISSUE THREAD

**Issue by nadejdashed** [pahen/madge#82]
After execution command "madge" I've received abdolute path of modules. Please see attached screenshot
![image](https://cloud.githubusercontent.com/assets/5268035/15555989/211521a6-22d4-11e6-807b-60fd4d26e910.png)

I've added MR https://github.com/pahen/madge/pull/80 that could resolve the issue. Or could you please help me resolve this issue inother way. Thank you

**Comment by scuzzlebuzzle** [comment]
Having same problem on my Windows Server 2008 box.

**Comment by pahen** [comment]
Fixed in https://github.com/pahen/madge/commit/e0540a73c337fc9998ea738e59a51ed0dc087e44
