### ISSUE TITLE
Divergence between package.json and npm-shrinkwrap.json

### ISSUE THREAD

**Issue by pbialek** [pahen/madge#86]
There is a divergence between _package.json_ and _npm-shrinkwrap.json_ and installing _madge_ brings a lot of extraneous packages.
It's problematic and it force to use `npm prune` before generating _shrinkwrap_ in projects where _madge_ is used.

Please, synchronize these two files.

**Comment by pahen** [comment]
This is fixed in the master branch now (will be included in v0.5.5).
