### ISSUE TITLE
Feature request: Support reading from `.madge` or `madge` key in package.json

### ISSUE THREAD

**Issue by olalonde** [pahen/madge#88]
Would be nice if madge could read from `~/.madge` or a `madge` key in package.json to get default command line flags. For example, in an es6 project the `--es6` flag should always be set.

For now I added this line to my scripts in package.json:

```
    "madge": "madge --format es6 --exclude node_modules"
```

and use it as:

```
npm run madge -- --some-other-flag ./path/to/src/
```

But I have to repeat ./path/to/src/ each time because there isn't a flag for that AFAIK :(

**Comment by pahen** [comment]
Good idea! I think we can support both .madge and a "madge" property in package.json. I can take a look at it when I'm back from my vacation.
