### ISSUE TITLE
export x from './x' syntax not supported?

### ISSUE THREAD

**Issue by olalonde** [pahen/madge#89]
Seems madge doesn't understand "re-export" statements:

./a.js
```
export const helloStr = 'Hello World !'
export default () => console.log(helloStr)
```

./b.js
```
export helloWorld from './a'
```

./index.js
```
import * as b from './b'

b.helloWorld()
```

```
madge --format es6 --image graph.png ./
```

Results in the following dependency graph:

![graph](https://cloud.githubusercontent.com/assets/416585/16354599/edfd0e46-3a4d-11e6-9c2c-08eae8184cc3.png)

It seems as though nothing depends on `a.js` which is inaccurate.

**Comment by olalonde** [comment]
Sent a PR to node-detective-es6, https://github.com/mrjoelkemp/node-detective-es6/pull/8 ... hopefully that fixes the issue.

**Comment by olalonde** [comment]
Wrote a PR that fixes this: https://github.com/pahen/madge/pull/91

**Comment by olalonde** [comment]
Image after PR:

![graph](https://cloud.githubusercontent.com/assets/416585/16354971/7ba87938-3a5d-11e6-8ef4-1306f6a37697.png)

**Comment by pahen** [comment]
Fixed in https://github.com/pahen/madge/commit/5deb37f062eb228f404910e8c6ceefb52986c6e4
