### ISSUE TITLE
Mage command just hangs: no error or progress.

### ISSUE THREAD

**Issue by alphapilgrim** [pahen/madge#92]
I ran the following: madge --image graph.png project/src/mymodule.js
It just hangs without it doing anything. Is there something im missing? Please help.

**Comment by pahen** [comment]
Can you give me some more details? What OS are you running? Is your project publicly available somewhere so I can test?

**Comment by alphapilgrim** [comment]
OSX - El Capitan
10.11.5
Not publicly ava.

**Comment by pahen** [comment]
What's the output of "madge project/src/mymodule.js" ?

**Comment by g-patel** [comment]
I ran into this today. thiking of running with --debug option next.
