### ISSUE TITLE
[bug?] No dependencies found

### ISSUE THREAD

**Issue by trusktr** [pahen/madge#93]
Madge seems to think my ES6 modules have zero dependencies:

```
infamous+infamous git:master ❯ madge --summary src
motor-html/node-style: 0
Calendar: 0
DoubleSidedPlane: 0
Grid: 0
Molecule: 0
Plane: 0
PushMenuLayout: 0
index: 0
jss/index: 0
motor-html/base: 0
motor-html/index: 0
motor-html/node: 0
Cube: 0
motor-html/push-pane-layout: 0
motor-html/scene: 0
motor-html/scene-style: 0
motor-html/web-component: 0
motor/Curves: 0
motor/Motor: 0
motor/Node: 0
motor/PushPaneLayout: 0
motor/Scene: 0
motor/Utility: 0
motor/index: 0
utils: 0
```

**Comment by mrjoelkemp** [comment]
Thanks for reporting @trusktr! Which version of madge are you on? 

Can you post a sample of one of the files that should have dependencies?

**Comment by pahen** [comment]
You must specify format with 'madge --format es6'

onsdag 6 juli 2016 skrev Joseph Orbegoso Pea <notifications@github.com>:

> Madge seems to think my ES6 modules have zero dependencies:
>
> infamous+infamous git:master ❯ madge --summary src
> motor-html/node-style: 0
> Calendar: 0
> DoubleSidedPlane: 0
> Grid: 0
> Molecule: 0
> Plane: 0
> PushMenuLayout: 0
> index: 0
> jss/index: 0
> motor-html/base: 0
> motor-html/index: 0
> motor-html/node: 0
> Cube: 0
> motor-html/push-pane-layout: 0
> motor-html/scene: 0
> motor-html/scene-style: 0
> motor-html/web-component: 0
> motor/Curves: 0
> motor/Motor: 0
> motor/Node: 0
> motor/PushPaneLayout: 0
> motor/Scene: 0
> motor/Utility: 0
> motor/index: 0
> utils: 0
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pahen/madge/issues/93>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAVmYLRxX_-75zcb3f6eG-0kQAt0F6rzks5qSv_ugaJpZM4JFqvR>
> .
>


-- 
/Patrik

**Comment by trusktr** [comment]
Ah, thanks, sorry. I subconsciously assumed it would auto-detect.

**Comment by pahen** [comment]
Nice :) Autodetection will hopefully get into v1.0.0 released soon.
