### ISSUE TITLE
Handling aliased modules (via Babel plugins)

### ISSUE THREAD

**Issue by jrnail23** [pahen/madge#99]
Hi, my project has quite a few modules imported as aliases, which we're handling via [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver).  Specifically, we're using it to simplify otherwise deeply nested `import` paths.

Unfortunately, I'm not quite clear on how to get such dependencies to show up in Madge.

Here's a simplified example:

Given this folder structure:
```
-src
  -components
    -component-a
    -component-b
      -stuff
        -more-stuff
          -my-view.js
```

You might see the following in `src/components/component-b/stuff/more-stuff/my-view.js`:
```js
import componentA from 'components/component-a'
```
instead of
```js
import componentA from `../../../component-a`
```

When I change the `componentA` import to use a relative path (like the 2nd part of the example), that dependency shows up just fine in Madge.  The first approach, however, gets ignored entirely.

Can anyone suggest a way to correctly apply the babel plugin to get Madge to use the proper import/require paths?  I suspect it will involve the `requireConfig` setting, but I haven't been able to find the secret sauce just yet, since adding even an empty `requireConfig` significantly changes the tree generated by Madge.

**Comment by mrjoelkemp** [comment]
Hi @jrnail23. Thanks for contributing!

If you try setting the `baseUrl` of the require config to `src/`, that should resolve `components/component-a`.

Can you provide the command and configuration that you're using to invoke Madge? Once you provide that, I can give you more detailed instructions.

**Comment by mrjoelkemp** [comment]
@pahen Can we close this until we get more info?

**Comment by pahen** [comment]
Yes, I agree. I'll close it.
